apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: profiles-system

helmCharts:
- name: pyroscope
  repo: https://grafana.github.io/helm-charts
  releaseName: pyroscope
  namespace: profiles-system
  includeCRDs: false
  additionalValuesFiles:
  - values-k3d-k3s.yaml

resources:
- namespace.yaml
