
services:
  agent-all-in-one:
    labels:
      logs.agent.grafana.com/log-format: logfmt
      app: grafana-agent
    depends_on:
      gateway:
        condition: service_healthy
    image: ${AGENT_IMAGE:-docker.io/grafana/agent:latest}
    volumes:
      - ../config/agent-flow:/etc/agent-config
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint:
      - /bin/grafana-agent
      - run
      - /etc/agent-config/monolithic-mode-all.river
      - --server.http.listen-addr=0.0.0.0:12345
      - --cluster.enabled=true
      - --disable-reporting=true
    environment:
      - AGENT_MODE=flow
      - AGENT_CONFIG_FOLDER=/etc/agent-config
    # expose 12345 port so we can directly access grafana-agent inside container
    ports:
      - "12345:12345"
