services:
  load-tempo-rules:
    depends_on:
      gateway:
        condition: service_started
    image: grafana/mimirtool:2.11.0
    volumes:
      - ../../../monitoring-mixins/tempo-mixin/deploy/rules.yaml:/tempo-mixin/rules.yaml
      - ../../../monitoring-mixins/tempo-mixin/deploy/alerts.yaml:/tempo-mixin/alerts.yaml
    environment:
      - MIMIR_ADDRESS=http://gateway:8080
      - MIMIR_TENANT_ID=anonymous
    command: >-
      rules load /tempo-mixin/rules.yaml /tempo-mixin/alerts.yaml
  