services:
  load-tempo-rules:
    depends_on:
      gateway:
        condition: service_started
    image: ${MIMIRTOOL_IMAGE:-docker.io/grafana/mimirtool:latest}
    volumes:
      - ../../../monitoring-mixins/tempo-mixin/deploy/tempo-mixin-rules.yaml:/tempo-mixin-rules.yaml
      - ../../../monitoring-mixins/tempo-mixin/deploy/tempo-mixin-alerts.yaml:/tempo-mixin-alerts.yaml
    environment:
      - MIMIR_ADDRESS=http://gateway:8080
      - MIMIR_TENANT_ID=anonymous
    command: >-
      rules load /tempo-mixin-rules.yaml /tempo-mixin-alerts.yaml
  