
services:
  memcached:
    labels:
      - metrics.grafana.com/scrape=false
    image: ${MEMCACHED_IMAGE:-docker.io/memcached:1.6.24-alpine}

  memcached-exporter:
    labels:
      - logs.grafana.com/scrape=false
      - metrics.grafana.com/scrape=true
      # - metrics.grafana.com/job=memcached
      - metrics.grafana.com/port=9150
      - metrics.grafana.com/interval=15s
    image: ${MEMCACHED_EXPORTER_IMAGE:-prom/memcached-exporter:v0.14.2}
    command:
      - --memcached.address=memcached:11211
      - --web.listen-address=0.0.0.0:9150
