
services:
  minio:
    # https://github.com/qclaogui/codelab-monitoring/blob/main/docker-compose/common/config/agent-flow/modules/docker/README.md
    labels:
      - logs.agent.grafana.com/scrape=false
      - metrics.agent.grafana.com/scrape=true
      - metrics.agent.grafana.com/job=minio-job
      - metrics.agent.grafana.com/path=/minio/v2/metrics/cluster
      - metrics.agent.grafana.com/port=9000
      - metrics.agent.grafana.com/interval=15s
      - metrics.agent.grafana.com/timeout=10s
    image: ${MINIO_IMAGE:-docker.io/minio/minio:RELEASE.2024-03-15T01-07-19Z}
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /data/mimir-blocks /data/mimir-ruler /data/mimir-alertmanager && \
        mkdir -p /data/loki-data /data/loki-ruler && \
        mkdir -p /data/tempo-data  && \
        mkdir -p /data/pyroscope-data && \
        minio server /data --console-address ':9001'
    environment:
      - MINIO_ROOT_USER=lgtmp
      - MINIO_ROOT_PASSWORD=supersecret
      - MINIO_PROMETHEUS_AUTH_TYPE=public
      - MINIO_UPDATE=off
      # # https://github.com/minio/console/issues/3237#issuecomment-1947485286
      # - MINIO_PROMETHEUS_URL="http://gateway:8080/prometheus"
      # - MINIO_PROMETHEUS_JOB_ID="minio-job"
    volumes:
      - data-minio:/data:delegated
    healthcheck:
      test: ["CMD-SHELL", "mc ready local"]
      interval: 5s
      timeout: 2s
      retries: 5
    ports:
      - "9001:9001"

volumes:
  data-minio:
    driver: local

