
services:
  minio:
    image: minio/minio:RELEASE.2024-03-05T04-48-44Z
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /data/mimir-blocks /data/mimir-ruler /data/mimir-alertmanager && \
        mkdir -p /data/loki-data /data/loki-ruler && \
        mkdir -p /data/tempo-data  && \
        mkdir -p /data/pyroscope-data && \
        minio server /data --console-address ':9001'
    environment:
      - MINIO_ROOT_USER=lgtmp
      - MINIO_ROOT_PASSWORD=supersecret
      - MINIO_PROMETHEUS_AUTH_TYPE=public
      - MINIO_UPDATE=off
      # # Using /minio/v2/metrics is not supported yet with console. https://github.com/minio/console/issues/629#issuecomment-792055977
      # - MINIO_PROMETHEUS_URL="http://gateway:8080/prometheus"
      # - MINIO_PROMETHEUS_JOB_ID="integrations/minio"
    volumes:
      - data-minio:/data:delegated
    # Fix health check https://github.com/minio/minio/issues/18373#issuecomment-1790003599
    healthcheck:
      test: timeout 5s bash -c ':> /dev/tcp/127.0.0.1/9000' || exit 1
      interval: 5s
      retries: 1
      start_period: 5s
      timeout: 5s
    ports:
      - "9001:9001"

volumes:
  data-minio:
    driver: local

