# ============================================================================ #
#                  Microservices Mode - Profiles
# ============================================================================ #

# ----------------------------------------------------
# apiVersion and kind of Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../common/grafana-agent
- pyroscope

# optional
- ../../monolithic-mode/metrics/mimir


secretGenerator:
- name: pyroscope-env
  namespace: profiles-system
  literals:
  - PYROSCOPE_STORAGE_S3_SECRET_ACCESS_KEY=VD538OYxSEiGD4I9mmFfqFMCGq1vIiGm

configMapGenerator:
- name: agent-config
  namespace: monitoring-system
  behavior: replace
  files:
  - configs/config.river

- name: pyroscope-config
  namespace: profiles-system
  options:
    disableNameSuffixHash: true
  behavior: replace
  files:
  - config.yaml=configs/pyroscope.yaml

# Update Pyroscope Microservices Mode endpoint in gateway
- name: nginx-env
  namespace: gateway
  options:
    disableNameSuffixHash: true
  literals:
  - PYROSCOPE_DISTRIBUTOR_HOST=pyroscope-distributor.profiles-system.svc.cluster.local
  - PYROSCOPE_QUERY_FRONTEND_HOST=pyroscope-query-frontend.profiles-system.svc.cluster.local
