# ============================================================================ #
#                  Microservices Mode - Profiles
# ============================================================================ #

# ----------------------------------------------------
# apiVersion and kind of Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- pyroscope

secretGenerator:
# https://grafana.com/docs/pyroscope/latest/configure-server/reference-configuration-parameters/#s3_storage_backend
- name: pyroscope-env
  namespace: profiles-system
  literals:
  - PYROSCOPE_STORAGE_S3_SECRET_ACCESS_KEY=VD538OYxSEiGD4I9mmFfqFMCGq1vIiGm


configMapGenerator:
- name: grafana-datasources
  namespace: monitoring-system
  options:
    disableNameSuffixHash: true
    labels:
      grafana_datasource: "1"
  files:
  - datasources.yaml=configs/grafana-datasources-pyroscope.yaml

- name: pyroscope-config
  namespace: profiles-system
  options:
    disableNameSuffixHash: true
  behavior: replace
  files:
  - config.yaml=configs/pyroscope.yaml

# replace nginx-templates and nginx-env configMap
- name: nginx-templates
  namespace: gateway
  options:
    disableNameSuffixHash: true
  files:
  - configs/gateway_pyroscope.conf.template
- name: nginx-env
  namespace: gateway
  options:
    disableNameSuffixHash: true
  # We need to fully set all variables because nginx envsubst does not support default values.
  # https://github.com/nginxinc/docker-nginx/issues/592
  literals:
  - PYROSCOPE_DISTRIBUTOR_HOST=pyroscope-distributor.profiles-system.svc.cluster.local
  - PYROSCOPE_QUERY_FRONTEND_HOST=pyroscope-query-frontend.profiles-system.svc.cluster.local
