analytics:
  reporting_enabled: false

storage:
  backend: s3
  s3:
    bucket_name: pyroscope-data
    endpoint: ${PYROSCOPE_STORAGE_S3_ENDPOINT:minio:9000}
    access_key_id: ${PYROSCOPE_STORAGE_S3_ACCESS_KEY_ID:admin}
    secret_access_key: ${PYROSCOPE_STORAGE_S3_SECRET_ACCESS_KEY:admin_password}
    insecure: false
    http:
      insecure_skip_verify: true
