apiVersion: 1

deleteDatasources:
- name: Profiles
  uid: profiles

datasources:
# Pyroscope for profiles
- name: Profiles
  type: grafana-pyroscope-datasource
  access: proxy
  orgId: 1
  uid: profiles
  url: http://gateway:4040
  basicAuth: false
  isDefault: true
  version: 1
  editable: true
