apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring-system

helmCharts:
- name: grafana-agent
  version: 0.27.2
  repo: https://grafana.github.io/helm-charts
  releaseName: grafana-agent
  namespace: monitoring-system
  includeCRDs: false
  valuesFile: values-k3d-k3s.yaml

configMapGenerator:
- name: grafana-agent-metrics-config
  files:
  - configs/metrics.river