apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tracing-system

helmCharts:
- name: tempo
  # version: 1.7.1
  repo: https://grafana.github.io/helm-charts
  releaseName: tempo
  namespace: tracing-system
  includeCRDs: false
  additionalValuesFiles:
  - values-k3d-k3s.yaml

resources:
- servicemonitor.yaml
- namespace.yaml
