apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tracing-system

helmCharts:
- name: tempo
  version: 1.7.2
  repo: https://grafana.github.io/helm-charts
  releaseName: tempo
  namespace: tracing-system
  includeCRDs: false
  additionalValuesFiles:
  - values-k3d-k3s.yaml

images:
- name: grafana/tempo
  newTag: 2.4.0

patches:
- patch: |-
    apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: tempo
      namespace: tracing-system
    spec:
      template:
        spec:
          containers:
            - name: tempo
              ports:
                - name: tempo-grpc
                  containerPort: 9095

- patch: |-
    apiVersion: v1
    kind: Service
    metadata:
      name: tempo
      namespace: tracing-system
    spec:
      ports:
        - name: tempo-grpc
          port: 9095
          targetPort: 9095

resources:
- servicemonitor.yaml
- namespace.yaml
