apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: tempo
  version: 1.7.1
  repo: https://grafana.github.io/helm-charts
  releaseName: tempo
  namespace: tracing-system
  includeCRDs: false
  valuesFile: values-k3d-k3s.yaml
