tempo:
  multitenancyEnabled: false
  reportingEnabled: false

  server:
    # -- HTTP server listen port
    http_listen_port: 3100
    grpc_listen_port: 9095

  metricsGenerator:
    enabled: true
    remoteWriteUrl: "http://nginx.gateway.svc.cluster.local:8080/api/v1/push"
  
  ingester:
    max_block_duration: 5m

  retention: 1h

  extraArgs:
    config.expand-env: true
  
  extraEnvFrom:
  - secretRef:
      name: tempo-env
