tempo:
  multitenancyEnabled: false
  reportingEnabled: false

  metricsGenerator:
    enabled: false
  
  ingester:
    max_block_duration: 5m

  retention: 1h

  extraArgs:
    config.expand-env: true
  
  extraEnvFrom:
  - secretRef:
      name: tempo-env

serviceMonitor:
  enabled: true
  interval: 15s
  additionalLabels: {}
  annotations: {}
