
auth:
  enabled: false
  username: "lgtmp"
  # password: "VD538OYxSEiGD4I9mmFfqFMCGq1vIiGm"
  existingSecret: integrations-mysql-secret

args:
- -m 256Mi
- --extended=modern,track_sizes
- -I 5m
- -c 16384
- -v
- -u 11211

resources:
  limits:
    memory: 320Mi
    cpu: 999m
  requests:
    memory: 64Mi
    cpu: 50m

podAnnotations:
  logs.agent.grafana.com/scrape: "true"
  logs.agent.grafana.com/scrub-level: "debug" # Boolean whether or not the level should be dropped from the log message (as it is a label).
