# ============================================================================ #
#                  Monolithic Mode - Metrics
# ============================================================================ #

# ----------------------------------------------------
# apiVersion and kind of Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- mimir/gossip-ring-headless-svc.yaml
- mimir/mimir-dep.yaml
- mimir/mimir-svc.yaml
- mimir/mimir-servicemonitor.yaml

# Horizontally scale up support(Monolithic mode)
# https://grafana.com/docs/mimir/latest/references/architecture/deployment-modes/#monolithic-mode
replicas:
- count: 1
  name: mimir

images:
- name: grafana/mimir
  newTag: 2.11.0

secretGenerator:
- name: mimir-env
  namespace: monitoring-system
  literals:
  - MIMIR_S3_SECRET_ACCESS_KEY=VD538OYxSEiGD4I9mmFfqFMCGq1vIiGm

configMapGenerator:
- name: agent-config
  namespace: monitoring-system
  options:
    disableNameSuffixHash: true
  files:
  - configs/config.river

- name: mimir-config
  namespace: monitoring-system
  files:
  - configs/mimir.yaml
- name: runtime-config
  namespace: monitoring-system
  files:
  - configs/runtime.yaml
