# ============================================================================ #
#                  Monolithic Mode - Metrics
# ============================================================================ #

# ----------------------------------------------------
# apiVersion and kind of Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../common/grafana-agent
- mimir

configMapGenerator:
- name: agent-config
  namespace: monitoring-system
  behavior: replace
  files:
  - configs/config.river
