# ----------------------------------------------------
# apiVersion and kind of Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- mimir/gossip-ring-headless-svc.yaml
- mimir/mimir-dep.yaml
- mimir/mimir-svc.yaml
- mimir/mimir-servicemonitor.yaml

images:
- name: grafana/mimir
  newTag: 2.10.4

# Horizontally scale up support(Monolithic mode)
# https://grafana.com/docs/mimir/latest/references/architecture/deployment-modes/#monolithic-mode
replicas:
- count: 1
  name: mimir

secretGenerator:
- name: agent-env
  namespace: monitoring-system
  options:
    disableNameSuffixHash: true
  literals:
  - CLUSTER=k3d-k3s-codelab
  - METRICS_ENDPOINT=http://nginx.gateway.svc.cluster.local:8080

- name: mimir-env
  namespace: monitoring-system
  literals:
  - MIMIR_S3_SECRET_ACCESS_KEY=VD538OYxSEiGD4I9mmFfqFMCGq1vIiGm

configMapGenerator:
- name: mimir-config
  namespace: monitoring-system
  files:
  - configs/mimir.yaml
- name: runtime-config
  namespace: monitoring-system
  files:
  - configs/runtime.yaml
