# ============================================================================ #
#                  Monolithic Mode - Metrics
# ============================================================================ #

# ----------------------------------------------------
# apiVersion and kind of Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- mimir

secretGenerator:
- name: mimir-env
  namespace: monitoring-system
  literals:
  - MIMIR_S3_SECRET_ACCESS_KEY=VD538OYxSEiGD4I9mmFfqFMCGq1vIiGm

configMapGenerator:
- name: agent-config
  namespace: monitoring-system
  options:
    disableNameSuffixHash: true
  files:
  - configs/config.river

- name: mimir-config
  namespace: monitoring-system
  files:
  - configs/mimir.yaml
- name: runtime-config
  namespace: monitoring-system
  files:
  - configs/runtime.yaml
