---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mimir
  name: mimir
  namespace: monitoring-system
spec:
  ports:
  - name: http-metrics
    port: 8080
  - name: grpc-distribut
    port: 9095
  selector:
    app: mimir
