apiVersion: 1

datasources:
# Mimir for metrics
- name: Metrics
  type: prometheus
  uid: metrics
  access: proxy
  orgId: 1
  url: http://gateway:8080/prometheus
  basicAuth: false
  isDefault: false
  version: 1
  editable: true
  jsonData:
    prometheusType: Mimir
    exemplarTraceIdDestinations:
      - name: traceID
        datasourceUid: traces

# Loki for logs
- name: Logs
  type: loki
  access: proxy
  orgId: 1
  uid: logs
  url: http://gateway:3100
  basicAuth: false
  isDefault: false
  version: 1
  editable: true

# Tempo for traces
- name: Traces
  type: tempo
  access: proxy
  orgId: 1
  uid: traces
  url: http://gateway:3200
  basicAuth: false
  isDefault: true # Note: default datasources
  version: 1
  editable: true
  apiVersion: 1
  jsonData:
    search:
      hide: false
    nodeGraph:
      enabled: true
    serviceMap:
      datasourceUid: metrics
    traceQuery:
      timeShiftEnabled: true
      spanStartTimeShift: '-30m'
      spanEndTimeShift: '30m'
    spanBar:
      type: 'Tag'
      tag: 'http.path'
    tracesToMetrics:
      datasourceUid: metrics
      spanStartTimeShift: '-30m'
      spanEndTimeShift: '30m'
      tags: [{ key: 'service.name', value: 'service' }, { key: 'span_name' }, { key: 'http_method' }]
      queries:
      - name: '(R) Rate'
        query: 'sum(rate(traces_spanmetrics_calls_total{$$__tags}[$$__rate_interval]))'
      - name: '(E) Error Rate'
        query: 'sum(rate(traces_spanmetrics_calls_total{$$__tags, status_code="STATUS_CODE_ERROR"}[$$__rate_interval]))'
      - name: '(D) Duration'
        query: 'histogram_quantile(0.9, sum(rate(traces_spanmetrics_latency_bucket{$$__tags}[$$__rate_interval])) by (le))'

# Pyroscope for profiles
- name: Profiles
  type: grafana-pyroscope-datasource
  access: proxy
  orgId: 1
  uid: profiles
  url: http://gateway:4040
  basicAuth: false
  isDefault: false # Note: default datasources
  version: 1
  editable: true
