usage_report:
  reporting_enabled: false

multitenancy_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095
  log_level: warn

distributor:
  receivers:                           # this configuration will listen on all ports and protocols that tempo is capable of.
    otlp:
      protocols:
        http:
        grpc:

ingester:
  max_block_duration: 5m               # cut the headblock when this much time passes. this is being set for demo purposes and should probably be left alone normally

memberlist:
  join_members:
  - tempo-memberlist:7946

compactor:
  ring:
    kvstore:
      store: memberlist
  compaction:
    block_retention: 1h                # overall Tempo trace retention. set for demo purposes

querier:
  frontend_worker:
    frontend_address: query-frontend:9095

storage:
  trace:
    backend: s3
    wal:
      path: /tmp/tempo/wal
    s3:
      bucket: tempo-data
      # endpoint: ${TEMPO_S3_ENDPOINT:minio:9000}
      # access_key: ${TEMPO_S3_ACCESS_KEY:lgtmp}
      # secret_key: ${TEMPO_S3_SECRET_KEY:supersecret}
      # insecure: ${TEMPO_S3_INSECURE:true}
      endpoint: minio:9000
      access_key: lgtmp
      secret_key: supersecret
      insecure: true
      tls_insecure_skip_verify: true
