multitenancy_enabled: false
usage_report:
  reporting_enabled: false

compactor:
  ring:
    kvstore:
      store: memberlist
  compaction:
    block_retention: 1h

distributor:
  receivers:
    otlp:
      protocols:
        http:
        grpc:

ingester:
  max_block_duration: 5m

memberlist:
  join_members:
  - tempo-memberlist:7946

querier:
  frontend_worker:
    frontend_address: query-frontend:9095

server:
  grpc_server_max_recv_msg_size: 4194304
  grpc_server_max_send_msg_size: 4194304
  http_listen_port: 3100
  grpc_listen_port: 9095
  log_level: info


storage:
  trace:
    backend: s3
    wal:
      path: /tmp/tempo/wal
    s3:
      bucket: tempo-data
      # endpoint: ${TEMPO_S3_ENDPOINT:minio:9000}
      # access_key: ${TEMPO_S3_ACCESS_KEY:lgtmp}
      # secret_key: ${TEMPO_S3_SECRET_KEY:supersecret}
      # insecure: ${TEMPO_S3_INSECURE:true}
      endpoint: minio:9000
      access_key: lgtmp
      secret_key: supersecret
      insecure: true
      tls_insecure_skip_verify: true
