usage_report:
  reporting_enabled: false

multitenancy_enabled: false

server:
  http_listen_port: 3200
  grpc_listen_port: 9095
  log_level: warn

distributor:
  receivers:                           # this configuration will listen on all ports and protocols that tempo is capable of.
    otlp:
      protocols:
        http:
        grpc:

ingester:
  max_block_duration: 5m               # cut the headblock when this much time passes. this is being set for demo purposes and should probably be left alone normally


compactor:
  compaction:
    block_retention: 1h                # overall Tempo trace retention. set for demo purposes

metrics_generator:
  registry:
    external_labels:
      cluster: docker-compose
      namespace: monitoring
  storage:
    path: /tmp/tempo/generator/wal
    remote_write:
    - url: http://mimir:8080/api/v1/push
      send_exemplars: true
      headers:
        X-Scope-OrgID: "anonymous"

storage:
  trace:
    backend: s3                     # backend configuration to use
    wal:
      path: /tmp/tempo/wal             # where to store the the wal locally
    s3:
      bucket: tempo-data
      endpoint: ${TEMPO_S3_ENDPOINT:minio:9000}
      access_key: ${TEMPO_S3_ACCESS_KEY:lgtmp}
      secret_key: ${TEMPO_S3_SECRET_KEY:supersecret}
      insecure: ${TEMPO_S3_INSECURE:true}
      tls_insecure_skip_verify: true