apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace: monitoring-system

helmCharts:
- name: mimir-distributed
  version: 5.1.3
  repo: https://grafana.github.io/helm-charts
  releaseName: mimir-distributed
  namespace: monitoring-system
  includeCRDs: false
  skipTests: true
  additionalValuesFiles:
  - values-k3d-k3s.yaml
