global:
  extraEnvFrom:
  - secretRef:
      name: mimir-distributed-env

minio:
  enabled: false

mimir:
  structuredConfig:
    multitenancy_enabled: false
    usage_stats:
      enabled: false

alertmanager:
  zoneAwareReplication:
    enabled: false

distributor:
  resources:
    requests:
      cpu: 10m
      memory: 64Mi

ingester:
  resources:
    requests:
      cpu: 10m
      memory: 128Mi
  zoneAwareReplication:
    enabled: false

overrides_exporter:
  resources:
    requests:
      cpu: 10m
      memory: 64Mi

ruler:
  resources:
    requests:
      cpu: 10m
      memory: 64Mi

querier:
  resources:
    requests:
      cpu: 10m
      memory: 64Mi

query_frontend:
  resources:
    requests:
      cpu: 10m
      memory: 64Mi

query_scheduler:
  resources:
    requests:
      cpu: 10m
      memory: 64Mi


store_gateway:
  resources:
    requests:
      cpu: 10m
      memory: 128Mi
  zoneAwareReplication:
    enabled: false

rollout_operator:
  enabled: false

nginx:
  enabled: false

metaMonitoring:
  dashboards:
    enabled: false
    annotations:
      grafana_dashboard_folder: "/dashboards/Mimir Dashboards"
  serviceMonitor:
    enabled: true
  prometheusRule:
    enabled: false
    mimirRules: false
    mimirAlerts: false
