global:
  extraEnvFrom:
  - secretRef:
      name: mimir-distributed-env

minio:
  enabled: false

mimir:
  structuredConfig:
    multitenancy_enabled: false
    usage_stats:
      enabled: false

ingester:
  zoneAwareReplication:
    enabled: false

store_gateway:
  zoneAwareReplication:
    enabled: false

alertmanager:
  zoneAwareReplication:
    enabled: false

rollout_operator:
  enabled: false

nginx:
  enabled: false

metaMonitoring:
  dashboards:
    enabled: false
    annotations:
      grafana_dashboard_folder: "/dashboards/Mimir Dashboards"
  serviceMonitor:
    enabled: false
  prometheusRule:
    enabled: false
    mimirRules: false
    mimirAlerts: false
