
# https://docs.docker.com/compose/multiple-compose-files/include/#include-and-overrides

# https://github.com/qclaogui/codelab-monitoring/blob/main/docker-compose/common/config/alloy/modules/compose/README.md
x-labels: &profiles-labels
  profiles.agent.grafana.com/cpu.scrape: true
  profiles.agent.grafana.com/memory.scrape: true
  profiles.agent.grafana.com/goroutine.scrape: true

x-environment: &jaeger-environment
  JAEGER_AGENT_HOST: alloy
  JAEGER_AGENT_PORT: 6831
  JAEGER_SAMPLER_TYPE: const
  JAEGER_SAMPLER_PARAM: 1

services:
  alloy: # override compose.yaml included service alloy entrypoint to use all-in-one.alloy. default(metrics.alloy)
    entrypoint:
      - /bin/alloy
      - run
      - /etc/alloy/all-in-one.alloy
      - --server.http.listen-addr=0.0.0.0:12345
      - --cluster.enabled=true
      - --cluster.join-addresses=alloy-cluster:12345
      - --disable-reporting=true
      - --stability.level=experimental
      - --storage.path=/var/lib/alloy/data

  # override compose.yaml included service loki's labels and environment to enabled profiles and traces data collection
  loki:
    labels:
      <<: *profiles-labels
      profiles.agent.grafana.com/service_name: loki
      logs.agent.grafana.com/log-format: json
    environment:
      <<: *jaeger-environment
      JAEGER_TAGS: app=loki

  # override compose.yaml included service grafana's labels and environment to enabled profiles data collection
  grafana:
    labels:
      <<: *profiles-labels
      profiles.agent.grafana.com/service_name: grafana
      profiles.agent.grafana.com/port: 6060
      logs.agent.grafana.com/log-format: logfmt
    volumes:
      - ./monitoring-mixins/pyroscope-mixin/deploy/dashboards_out:/var/lib/grafana/dashboards/pyroscope-mixin
      - ./monitoring-mixins/loki-mixin/deploy/dashboards_out:/var/lib/grafana/dashboards/loki-mixin
      - ./monitoring-mixins/tempo-mixin/deploy/dashboards_out:/var/lib/grafana/dashboards/tempo-mixin
    environment:
      GF_LOG_LEVEL: ${GF_LOG_LEVEL:-warn}
      GF_DIAGNOSTICS_PROFILING_ENABLED: true
      GF_DIAGNOSTICS_PROFILING_ADDR: 0.0.0.0
      GF_DIAGNOSTICS_PROFILING_PORT: 6060

  # override compose.yaml included service tempo's labels and environment to enabled profiles and traces data collection
  tempo:
    labels:
      <<: *profiles-labels
      profiles.agent.grafana.com/service_name: tempo
      logs.agent.grafana.com/log-format: logfmt
    depends_on: { minio: { condition: service_healthy }, mimir: { condition: service_healthy } }
    environment:
      <<: *jaeger-environment
      JAEGER_TAGS: app=tempo

  # override compose.yaml included service mimir's labels and environment to enabled profiles and traces data collection
  mimir:
    labels:
      <<: *profiles-labels
      profiles.agent.grafana.com/service_name: mimir
      logs.agent.grafana.com/log-format: logfmt
    environment:
      <<: *jaeger-environment
      JAEGER_TAGS: app=mimir

  # override included service mimirtool for rules and alerts pre-provisioning
  mimirtool:
    volumes:
      - ./monitoring-mixins/loki-mixin/deploy/loki-mixin-rules.yaml:/rules/loki-mixin-rules.yaml
      - ./monitoring-mixins/loki-mixin/deploy/loki-mixin-alerts.yaml:/rules/loki-mixin-alerts.yaml
      - ./monitoring-mixins/pyroscope-mixin/deploy/pyroscope-mixin-rules.yaml:/rules/pyroscope-mixin-rules.yaml
      - ./monitoring-mixins/tempo-mixin/deploy/tempo-mixin-rules.yaml:/rules/tempo-mixin-rules.yaml
      - ./monitoring-mixins/tempo-mixin/deploy/tempo-mixin-alerts.yaml:/rules/tempo-mixin-alerts.yaml

  # override compose.yaml included service pyroscope's labels and environment to enabled traces data collection
  pyroscope:
    labels:
      - logs.agent.grafana.com/log-format=logfmt
    environment:
      <<: *jaeger-environment
      JAEGER_TAGS: app=pyroscope
