apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# https://github.com/bitnami/charts/tree/main/bitnami/mysql/
helmCharts:
- name: mysql
  version: 9.14.4
  repo: oci://registry-1.docker.io/bitnamicharts
  releaseName: mysql
  namespace: mysql-system
  includeCRDs: false
  valuesFile: values-k3d-k3s.yaml

resources:
- namespace.yaml

# integrations mysql credentials
secretGenerator:
- name: integrations-mysql-secret
  namespace: mysql-system
  options:
    disableNameSuffixHash: true
  literals:
  - "mysql-host=mysql.mysql-system.svc.cluster.local"
  - "mysql-username=lgtmp"
  - "mysql-password=VD538OYxSEiGD4I9mmFfqFMCGq1vIiGm"
  - "mysql-root-password=mysqlrootpassword"
  - "mysql-replication-password=mysqlreplicationpassword"
