# ============================================================================ #
#                  Monolithic Mode - All in one
# ============================================================================ #

# ----------------------------------------------------
# apiVersion and kind of Kustomization
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../metrics/mimir
- ../logs/loki
- ../profiles/pyroscope
- ../traces/tempo
- ../../../monitoring-mixins/agent-flow-mixin/deploy
- ../../../monitoring-mixins/go-runtime-mixin/deploy
- ../../../monitoring-mixins/loki-mixin/deploy
- ../../../monitoring-mixins/mimir-mixin/deploy
# - ../../../monitoring-mixins/tempo-mixin/deploy

configMapGenerator:
- name: agent-config
  namespace: monitoring-system
  options:
    disableNameSuffixHash: true
  files:
  - configs/config.river

- name: grafana-datasources
  namespace: monitoring-system
  options:
    labels:
      grafana_datasource: "1"
  files:
  - datasources.yaml=configs/grafana-datasources-all-in-one.yaml

# Update LGTMP endpoint in gateway
- name: nginx-templates
  namespace: gateway
  options:
    disableNameSuffixHash: true
  files:
  - gateway_loki.conf.template=configs/gateway_loki.conf
  - gateway_mimir.conf.template=configs/gateway_mimir.conf
  - gateway_pyroscope.conf.template=configs/gateway_pyroscope.conf
  - gateway_tempo.conf.template=configs/gateway_tempo.conf
