# ============================================================================ #
#                  Monolithic Mode - All in one
# ============================================================================ #

# ----------------------------------------------------
# apiVersion and kind of Kustomization
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../common/grafana-agent
- ../logs/loki
- ../traces/tempo
- ../metrics/mimir
- ../profiles/pyroscope

configMapGenerator:
- name: agent-config
  namespace: monitoring-system
  behavior: replace
  files:
  - configs/config.river

# Update LGTMP endpoint in gateway
- name: nginx-templates
  namespace: gateway
  options:
    disableNameSuffixHash: true
  files:
  - gateway_loki.conf.template=configs/gateway_loki.conf
  - gateway_mimir.conf.template=configs/gateway_mimir.conf
  - gateway_pyroscope.conf.template=configs/gateway_pyroscope.conf
  - gateway_tempo.conf.template=configs/gateway_tempo.conf
