# ============================================================================ #
#                  Monolithic Mode - All in one
# ============================================================================ #

# ----------------------------------------------------
# apiVersion and kind of Kustomization
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../metrics/mimir
- ../logs/loki
- ../profiles/pyroscope
- ../traces/tempo

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: grafana-env
  namespace: monitoring-system
  literals:
  - GF_LOG_LEVEL=warn
  - GF_TRACING_OPENTELEMETRY_OTLP_ADDRESS=grafana-agent.monitoring-system:4317
  - GF_TRACING_OPENTELEMETRY_CUSTOM_ATTRIBUTES=service.namespace:monitoring-system
  - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor tracesEmbeddedFlameGraph traceqlSearch correlations metricsSummary traceToMetrics traceToProfiles

- name: loki-env
  namespace: logging-system
  literals:
  - LOKI_S3_SECRET_ACCESS_KEY=VD538OYxSEiGD4I9mmFfqFMCGq1vIiGm
  - JAEGER_SERVICE_NAME=loki
  - JAEGER_AGENT_HOST=grafana-agent.monitoring-system
  - JAEGER_AGENT_PORT=6831
  - JAEGER_SAMPLER_TYPE=const
  - JAEGER_SAMPLER_PARAM=1

- name: tempo-env
  namespace: tracing-system
  literals:
  - TEMPO_S3_SECRET_KEY=VD538OYxSEiGD4I9mmFfqFMCGq1vIiGm
  - JAEGER_SERVICE_NAME=tempo
  - JAEGER_AGENT_HOST=grafana-agent.monitoring-system
  - JAEGER_AGENT_PORT=6831
  - JAEGER_SAMPLER_TYPE=const
  - JAEGER_SAMPLER_PARAM=1

- name: mimir-env
  namespace: monitoring-system
  literals:
  - MIMIR_S3_SECRET_ACCESS_KEY=VD538OYxSEiGD4I9mmFfqFMCGq1vIiGm
  - JAEGER_SERVICE_NAME=mimir
  - JAEGER_AGENT_HOST=grafana-agent.monitoring-system
  - JAEGER_AGENT_PORT=6831
  - JAEGER_SAMPLER_TYPE=const
  - JAEGER_SAMPLER_PARAM=1

- name: pyroscope-env
  namespace: profiles-system
  literals:
  - PYROSCOPE_STORAGE_S3_SECRET_ACCESS_KEY=VD538OYxSEiGD4I9mmFfqFMCGq1vIiGm
  - JAEGER_SERVICE_NAME=pyroscope
  - JAEGER_AGENT_HOST=grafana-agent.monitoring-system
  - JAEGER_AGENT_PORT=6831
  - JAEGER_SAMPLER_TYPE=const
  - JAEGER_SAMPLER_PARAM=1

configMapGenerator:
- name: grafana-datasources
  namespace: monitoring-system
  options:
    labels:
      grafana_datasource: "1"
  files:
  - datasources.yaml=configs/grafana-datasources-all-in-one.yaml

- name: agent-config
  namespace: monitoring-system
  options:
    disableNameSuffixHash: true
  files:
  - configs/config.river

- name: loki-config
  namespace: logging-system
  behavior: replace
  files:
  - config.yaml=configs/loki.yaml

- name: mimir-config
  namespace: monitoring-system
  files:
  - configs/mimir.yaml
- name: runtime-config
  namespace: monitoring-system
  files:
  - runtime.yaml=configs/mimir-runtime.yaml

- name: pyroscope-config
  namespace: profiles-system
  behavior: replace
  files:
  - config.yaml=configs/pyroscope.yaml

- name: tempo
  namespace: tracing-system
  behavior: replace
  files:
  - configs/tempo.yaml
  - overrides.yaml=configs/tempo-overrides.yaml

# replace nginx-templates and nginx-env configMap
- name: nginx-templates
  namespace: gateway
  files:
  - configs/gateway_loki.conf.template
  - configs/gateway_mimir.conf.template
  - configs/gateway_pyroscope.conf.template
  - configs/gateway_tempo.conf.template
- name: nginx-env
  namespace: gateway
  envs:
  - configs/nginx.env
