version: '3.9'

# ============================================================================ #
#                  Microservices Mode - Traces
# ============================================================================ #

# Note: 
# include is available in Docker Compose version 2.20 and later, and Docker Desktop version 4.22 and later.
# docs: https://docs.docker.com/compose/multiple-compose-files/include/#include-and-overrides
include:
  - path: ../../common/compose-include/minio.yaml
  - path: ../../common/compose-include/memcached.yaml
  - path: ../../common/compose-include/mimir.yaml
  - path: ../../common/compose-include/loki.yaml
  - path:
      - ../../common/compose-include/grafana-agent.yaml
      - ./compose.override.yaml  # Microservices Mode services override
  - path: ../../common/compose-include/grafana.yaml

x-environment: &jaeger-environment
  JAEGER_AGENT_HOST: grafana-agent
  JAEGER_AGENT_PORT: 6831
  JAEGER_SAMPLER_TYPE: const
  JAEGER_SAMPLER_PARAM: 1

services:
  gateway:
    # https://github.com/qclaogui/codelab-monitoring/blob/main/docker-compose/common/config/agent-flow/modules/docker/README.md
    labels:
      metrics.agent.grafana.com/scrape: false
    depends_on:
      distributor:
        condition: service_healthy
    image: ${NGINX_IMAGE:-docker.io/nginxinc/nginx-unprivileged:1.25-alpine}
    restart: always
    volumes:
      - ../../common/config/nginx/10-default-lgtmp.envsh:/docker-entrypoint.d/10-default-lgtmp.envsh
      - ../../common/config/nginx/nginx.conf:/etc/nginx/templates/nginx.conf.template
      - ../../common/config/tempo/gateway_tempo.conf:/etc/nginx/templates/gateway_tempo.conf.template
      - ../../common/config/mimir/gateway_mimir.conf:/etc/nginx/templates/gateway_mimir.conf.template
      - ../../common/config/loki/gateway_loki.conf:/etc/nginx/templates/gateway_loki.conf.template
    environment:
      - TEMPO_DISTRIBUTOR_HOST=distributor
      - TEMPO_INGESTER_HOST=ingester
      - TEMPO_QUERY_FRONTEND_HOST=query-frontend
      - TEMPO_COMPACTOR_HOST=compactor
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3200/ || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - "33200:3200"

  distributor:
    depends_on:
      ingester:
        condition: service_started
    image: &tempoImage ${TEMPO_IMAGE:-docker.io/grafana/tempo:2.4.1}
    volumes:
      - ../../common/config/tempo:/etc/tempo
    command:
      - -config.file=/etc/tempo/microservices-mode-traces.yaml
      - -target=distributor
      - -config.expand-env=true
    environment:
      <<: *jaeger-environment
      JAEGER_TAGS: app=distributor
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3200/ready || exit 1" ]
      interval: 15s
      timeout: 10s
      retries: 10

  ingester:
    depends_on:
      minio:
        condition: service_healthy
    image: *tempoImage
    volumes:
      - ../../common/config/tempo:/etc/tempo
    command:
      - -config.file=/etc/tempo/microservices-mode-traces.yaml
      - -target=ingester
      - -config.expand-env=true
    environment:
      <<: *jaeger-environment
      JAEGER_TAGS: app=ingester
    deploy:
      replicas: 3
    networks:
      default:
        aliases:
          - tempo-memberlist

  query-frontend:
    depends_on:
      minio:
        condition: service_healthy
    image: *tempoImage
    volumes:
      - ../../common/config/tempo:/etc/tempo
    command:
      - -config.file=/etc/tempo/microservices-mode-traces.yaml
      - -target=query-frontend
      - -config.expand-env=true
    environment:
      <<: *jaeger-environment
      JAEGER_TAGS: app=query-frontend

  querier:
    depends_on:
      minio:
        condition: service_healthy
      query-frontend:
        condition: service_started
    image: *tempoImage
    volumes:
      - ../../common/config/tempo:/etc/tempo
    command:
      - -config.file=/etc/tempo/microservices-mode-traces.yaml
      - -target=querier
      - -config.expand-env=true
    environment:
      <<: *jaeger-environment
      JAEGER_TAGS: app=querier

  compactor:
    depends_on:
      minio:
        condition: service_healthy
    image: *tempoImage
    volumes:
      - ../../common/config/tempo:/etc/tempo
    command:
      - -config.file=/etc/tempo/microservices-mode-traces.yaml
      - -target=compactor
      - -config.expand-env=true
    environment:
      <<: *jaeger-environment
      JAEGER_TAGS: app=compactor
