version: '3.9'

# Note: 
# include is available in Docker Compose version 2.20 and later, and Docker Desktop version 4.22 and later.
include:
  - path: ../../common/compose-include/minio.yaml

# Monolithic mode (Metrics + Logs + Traces + Profiles)
services:
  agent:
    depends_on:
      tempo:
        condition: service_started
      mimir:
        condition: service_healthy
      loki:
        condition: service_healthy
    image: grafana/agent:v0.39.0
    volumes:
      - ../../common/config/agent-flow:/etc/agent-config
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint:
      - /bin/grafana-agent
      - run
      - /etc/agent-config/monolithic-mode-all.river
      - --server.http.listen-addr=0.0.0.0:12345
      - --cluster.enabled=true
      - --disable-reporting=true
    environment:
      - AGENT_MODE=flow
      - AGENT_CONFIG_FOLDER=/etc/agent-config
    ports:
      - "12345:12345"

  mimir:
    depends_on:
      minio:
        condition: service_healthy
    image: grafana/mimir:2.11.0
    volumes:
      - ../../common/config/mimir/monolithic-mode-metrics.yaml:/etc/config.yaml
    command:
      - -config.file=/etc/config.yaml
      - -target=all
      - -config.expand-env=true
      - -log.level=error
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/ready || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      replicas: 1
    networks:
      default:
        aliases:
          - mimir-memberlist

  load-mimir-rules:
    depends_on:
      mimir:
        condition: service_healthy
    image: grafana/mimirtool:2.11.0
    volumes:
      - ../../../monitoring-mixins/mimir-mixin/deploy/rules.yaml:/mimir-mixin/rules.yaml
      - ../../../monitoring-mixins/mimir-mixin/deploy/alerts.yaml:/mimir-mixin/alerts.yaml
    environment:
      - MIMIR_ADDRESS=http://mimir:8080
      - MIMIR_TENANT_ID=anonymous
    command: >-
      rules load /mimir-mixin/rules.yaml /mimir-mixin/alerts.yaml

  loki:
    depends_on:
      minio:
        condition: service_healthy
    image: grafana/loki:2.9.3
    volumes:
      - ../../common/config/loki/monolithic-mode-logs.yaml:/etc/config.yaml
    command:
      - -config.file=/etc/config.yaml
      - -target=all
      - -config.expand-env=true
      - -log.level=error
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      replicas: 1
    networks:
      default:
        aliases:
          - loki-memberlist

  load-loki-rules:
    depends_on:
      loki:
        condition: service_healthy
    image: grafana/mimirtool:2.11.0
    volumes:
      - ../../../monitoring-mixins/loki-mixin/deploy/rules.yaml:/loki-mixin/rules.yaml
      - ../../../monitoring-mixins/loki-mixin/deploy/alerts.yaml:/loki-mixin/alerts.yaml
    environment:
      - MIMIR_ADDRESS=http://mimir:8080
      - MIMIR_TENANT_ID=anonymous
    command: >-
      rules load /loki-mixin/rules.yaml /loki-mixin/alerts.yaml

  tempo:
    depends_on:
      minio:
        condition: service_healthy
      mimir:
        condition: service_healthy
    image: grafana/tempo:2.3.1
    volumes:
      - ../../common/config/tempo/monolithic-mode-traces.yaml:/etc/config.yaml
    environment:
      - TEMPO_S3_ENDPOINT=minio:9000
      - TEMPO_S3_ACCESS_KEY=lgtmp
      - TEMPO_S3_SECRET_KEY=supersecret
      - TEMPO_S3_INSECURE=true
    command:
      - -config.file=/etc/config.yaml
      - -target=all
      - -config.expand-env=true
      - -log.level=error
    ports:
      - "3200"
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3200/ready || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  load-tempo-rules:
    depends_on:
      tempo:
        condition: service_healthy
    image: grafana/mimirtool:2.11.0
    volumes:
      - ../../../monitoring-mixins/tempo-mixin/deploy/rules.yaml:/tempo-mixin/rules.yaml
      - ../../../monitoring-mixins/tempo-mixin/deploy/alerts.yaml:/tempo-mixin/alerts.yaml
    environment:
      - MIMIR_ADDRESS=http://mimir:8080
      - MIMIR_TENANT_ID=anonymous
    command: >-
      rules load /tempo-mixin/rules.yaml /tempo-mixin/alerts.yaml

  pyroscope:
    image: grafana/pyroscope:1.3.0
    volumes:
      - ../../common/config/pyroscope/monolithic-mode-profiles.yaml:/etc/config.yaml
    environment:
      - PYROSCOPE_STORAGE_S3_ENDPOINT=minio:9000
      - PYROSCOPE_STORAGE_S3_ACCESS_KEY_ID=lgtmp
      - PYROSCOPE_STORAGE_S3_SECRET_ACCESS_KEY=supersecret
      - PYROSCOPE_STORAGE_S3_INSECURE=true
    command:
      - -config.file=/etc/config.yaml
      - -config.expand-env=true
      - -log.level=warn
    # ports:
    #   - "4040:4040"

  grafana:
    image: grafana/grafana:10.2.3
    command:
      - --config=/etc/grafana-config/grafana.ini
    volumes:
      - ../../common/config/grafana/grafana.ini:/etc/grafana-config/grafana.ini
      - ../../common/config/grafana/dashboards:/var/lib/grafana/dashboards
      - ../../common/config/grafana/provisioning:/etc/grafana/provisioning
      - ./config/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ../../../monitoring-mixins/mimir-mixin/deploy/dashboards_out:/var/lib/grafana/dashboards/mimir-mixin  # load mimir dashboards
      - ../../../monitoring-mixins/loki-mixin/deploy/dashboards_out:/var/lib/grafana/dashboards/loki-mixin    # load loki dashboards
      - ../../../monitoring-mixins/tempo-mixin/deploy/dashboards_out:/var/lib/grafana/dashboards/tempo-mixin  # load tempo dashboards
    environment:
      - GF_LOG_LEVEL=error
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-admin_password}
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor,pyroscopeFlameGraph
      - GF_DIAGNOSTICS_PROFILING_ENABLED=true
      - GF_DIAGNOSTICS_PROFILING_ADDR=0.0.0.0
      - GF_DIAGNOSTICS_PROFILING_PORT=6060
      - GF_TRACING_OPENTELEMETRY_OTLP_ADDRESS=agent:4317
      - GF_TRACING_OPENTELEMETRY_CUSTOM_ATTRIBUTES=cluster:docker-compose,namespace:monitoring
      # - GF_INSTALL_PLUGINS=pyroscope-datasource,pyroscope-panel
    ports:
      - "3000:3000"

