version: '3.9'

# ============================================================================ #
#                  Monolithic Mode - All in one
# ============================================================================ #

# Note: 
# include is available in Docker Compose version 2.20 and later, and Docker Desktop version 4.22 and later.
include:
  - path: ../../common/compose-include/minio.yaml

x-environment: &jaeger-environment
  JAEGER_AGENT_HOST: agent
  JAEGER_AGENT_PORT: 6831
  JAEGER_SAMPLER_TYPE: const
  JAEGER_SAMPLER_PARAM: 1

services:
  agent:
    labels:
      - logs.agent.grafana.com/log-format=logfmt
      - app=grafana-agent
    depends_on:
      tempo:
        condition: service_started
      mimir:
        condition: service_healthy
      loki:
        condition: service_healthy
    image: ${AGENT_IMAGE:-docker.io/grafana/agent:latest}
    volumes:
      - ../../common/config/agent-flow:/etc/agent-config
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint:
      - /bin/grafana-agent
      - run
      - /etc/agent-config/monolithic-mode-all.river
      - --server.http.listen-addr=0.0.0.0:12345
      - --cluster.enabled=true
      - --disable-reporting=true
    environment:
      - AGENT_MODE=flow
      - AGENT_CONFIG_FOLDER=/etc/agent-config
    # expose 12345 port so we can directly access grafana-agent inside container
    ports:
      - "12345:12345"

  mimir:
    labels:
      - logs.agent.grafana.com/log-format=logfmt
    depends_on:
      minio:
        condition: service_healthy
    image: ${MIMIR_IMAGE:-docker.io/grafana/mimir:latest}
    volumes:
      - ../../common/config/mimir/monolithic-mode-metrics.yaml:/etc/config.yaml
    command:
      - -config.file=/etc/config.yaml
      - -target=all
      - -config.expand-env=true
      - -ruler.max-rules-per-rule-group=50
    environment:
      <<: *jaeger-environment
      JAEGER_TAGS: app=mimir
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/ready || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    # expose 38080 port so we can directly access mimir inside container
    ports:
      - "38080:8080"
    networks:
      default:
        aliases:
          - mimir-memberlist

  load-rules-to-mimir:
    depends_on:
      mimir:
        condition: service_healthy
    image: ${MIMIRTOOL_IMAGE:-docker.io/grafana/mimirtool:latest}
    volumes:
      - ../../../monitoring-mixins/agent-flow-mixin/deploy/agent-flow-mixin-alerts.yaml:/agent-flow-mixin-alerts.yaml
      - ../../../monitoring-mixins/loki-mixin/deploy/loki-mixin-rules.yaml:/loki-mixin-rules.yaml
      - ../../../monitoring-mixins/loki-mixin/deploy/loki-mixin-alerts.yaml:/loki-mixin-alerts.yaml
      - ../../../monitoring-mixins/memcached-mixin/deploy/memcached-mixin-alerts.yaml:/memcached-mixin-alerts.yaml
      - ../../../monitoring-mixins/mimir-mixin/deploy/mimir-mixin-rules.yaml:/mimir-mixin-rules.yaml
      - ../../../monitoring-mixins/mimir-mixin/deploy/mimir-mixin-alerts.yaml:/mimir-mixin-alerts.yaml
      - ../../../monitoring-mixins/pyroscope-mixin/deploy/pyroscope-mixin-rules.yaml:/pyroscope-mixin-rules.yaml
      # - ../../../monitoring-mixins/tempo-mixin/deploy/tempo-mixin-rules.yaml:/tempo-mixin-rules.yaml
      # - ../../../monitoring-mixins/tempo-mixin/deploy/tempo-mixin-alerts.yaml:/tempo-mixin-alerts.yaml
    environment:
      - MIMIR_ADDRESS=http://mimir:8080
      - MIMIR_TENANT_ID=anonymous
    command: >-
      rules load agent-flow-mixin-alerts.yaml /loki-mixin-rules.yaml /loki-mixin-alerts.yaml /memcached-mixin-alerts.yaml /mimir-mixin-rules.yaml /mimir-mixin-alerts.yaml /pyroscope-mixin-rules.yaml

  loki:
    # https://github.com/qclaogui/codelab-monitoring/blob/main/docker-compose/common/config/agent-flow/modules/docker/README.md
    labels:
      - logs.agent.grafana.com/log-format=json
      - profiles.agent.grafana.com/cpu.scrape=true
      - profiles.agent.grafana.com/memory.scrape=true
      - profiles.agent.grafana.com/goroutine.scrape=true
      - profiles.agent.grafana.com/service_name=loki
    depends_on:
      minio:
        condition: service_healthy
    image: ${LOKI_IMAGE:-docker.io/grafana/loki:latest}
    volumes:
      - ../../common/config/loki/monolithic-mode-logs.yaml:/etc/config.yaml
    command:
      - -config.file=/etc/config.yaml
      - -target=all
      - -config.expand-env=true
    environment:
      <<: *jaeger-environment
      JAEGER_TAGS: app=loki
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    # expose 33100 port so we can directly access loki inside container
    ports:
      - "33100:3100"
    networks:
      default:
        aliases:
          - loki-memberlist

  tempo:
    # https://github.com/qclaogui/codelab-monitoring/blob/main/docker-compose/common/config/agent-flow/modules/docker/README.md
    labels:
      - logs.agent.grafana.com/log-format=logfmt
      - profiles.agent.grafana.com/cpu.scrape=true
      - profiles.agent.grafana.com/memory.scrape=true
      - profiles.agent.grafana.com/goroutine.scrape=true
      - profiles.agent.grafana.com/service_name=tempo
    depends_on:
      minio:
        condition: service_healthy
      mimir:
        condition: service_healthy
    image: ${TEMPO_IMAGE:-docker.io/grafana/tempo:latest}
    volumes:
      - ../../common/config/tempo/monolithic-mode-traces.yaml:/etc/config.yaml
    command:
      - -config.file=/etc/config.yaml
      - -target=all
      - -config.expand-env=true
    environment:
      <<: *jaeger-environment
      JAEGER_TAGS: app=tempo
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3200/ready || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    # expose 33200 port so we can directly access tempo inside container
    ports:
      - "33200:3200"

  pyroscope:
    labels:
      - logs.agent.grafana.com/log-format=logfmt
    depends_on:
      minio:
        condition: service_healthy
    image: ${PYROSCOPE_IMAGE:-docker.io/grafana/pyroscope:latest}
    container_name: pyroscope
    volumes:
      - ../../common/config/pyroscope/monolithic-mode-profiles.yaml:/etc/config.yaml
    command:
      - -config.file=/etc/config.yaml
      - -config.expand-env=true
    # expose 34040 port so we can directly access pyroscope inside container
    ports:
      - "34040:4040"

  grafana:
    labels:
      - logs.agent.grafana.com/log-format=logfmt
    image: ${GRAFANA_IMAGE:-docker.io/grafana/grafana:latest}
    command:
      - --config=/etc/grafana-config/grafana.ini
    volumes:
      - ../../common/config/grafana/grafana.ini:/etc/grafana-config/grafana.ini
      - ../../common/config/grafana/dashboards:/var/lib/grafana/dashboards
      - ../../common/config/grafana/provisioning:/etc/grafana/provisioning
      - ./config/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ../../../monitoring-mixins/agent-flow-mixin/deploy/dashboards_out:/var/lib/grafana/dashboards/agent-flow-mixin
      - ../../../monitoring-mixins/go-runtime-mixin/deploy/dashboards_out:/var/lib/grafana/dashboards/go-runtime-mixin
      - ../../../monitoring-mixins/loki-mixin/deploy/dashboards_out:/var/lib/grafana/dashboards/loki-mixin
      - ../../../monitoring-mixins/mimir-mixin/deploy/dashboards_out:/var/lib/grafana/dashboards/mimir-mixin
      - ../../../monitoring-mixins/pyroscope-mixin/deploy/dashboards_out:/var/lib/grafana/dashboards/pyroscope-mixin
      # - ../../../monitoring-mixins/tempo-mixin/deploy/dashboards_out:/var/lib/grafana/dashboards/tempo-mixin
    environment:
      - GF_LOG_LEVEL=warn
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-admin_password}
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor tracesEmbeddedFlameGraph traceqlSearch correlations metricsSummary traceToMetrics traceToProfiles
    ports:
      - "3000:3000"

