
services:
  # override included service grafana for dashboards pre-provisioning
  grafana:
    labels:
      profiles.agent.grafana.com/cpu.scrape: true
      profiles.agent.grafana.com/memory.scrape: true
      profiles.agent.grafana.com/goroutine.scrape: true
      profiles.agent.grafana.com/service_name: grafana
      profiles.agent.grafana.com/port: 6060
      logs.agent.grafana.com/log-format: logfmt
    volumes:
      - ../../../monitoring-mixins/pyroscope-mixin/deploy/dashboards_out:/var/lib/grafana/dashboards/pyroscope-mixin
      - ../../../monitoring-mixins/loki-mixin/deploy/dashboards_out:/var/lib/grafana/dashboards/loki-mixin
      # - ../../../monitoring-mixins/tempo-mixin/deploy/dashboards_out:/var/lib/grafana/dashboards/tempo-mixin
    environment:
      GF_LOG_LEVEL: ${GF_LOG_LEVEL:-warn}
      GF_DIAGNOSTICS_PROFILING_ENABLED: true
      GF_DIAGNOSTICS_PROFILING_ADDR: 0.0.0.0
      GF_DIAGNOSTICS_PROFILING_PORT: 6060
