multitenancy_enabled: false
usage_report:
  reporting_enabled: false
compactor:
  compaction:
    block_retention: 1h
  ring:
    kvstore:
      store: memberlist

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
  ring:
    kvstore:
      store: memberlist

ingester:
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      replication_factor: 1
    tokens_file_path: /var/tempo/tokens.json
  max_block_duration: 5m

memberlist:
  join_members:
  - dns+tempo-distributed-gossip-ring:7946

overrides:
  per_tenant_override_config: /runtime-config/overrides.yaml

querier:
  frontend_worker:
    frontend_address: tempo-distributed-query-frontend-discovery:9095
  max_concurrent_queries: 20
query_frontend:
  max_retries: 2
  search:
    duration_slo: 5s
    throughput_bytes_slo: 1.073741824e+09
  trace_by_id:
    duration_slo: 5s
server:
  grpc_server_max_recv_msg_size: 4194304
  grpc_server_max_send_msg_size: 4194304
  http_listen_port: 3100
  grpc_listen_port: 9095
  log_format: logfmt
  log_level: info
storage:
  trace:
    backend: s3
    wal:
      path: /var/tempo/wal
    s3:
      bucket: tempo-data
      endpoint: ${TEMPO_S3_ENDPOINT:minio.minio-system.svc:443}
      access_key: ${TEMPO_S3_ACCESS_KEY:lgtmp}
      secret_key: ${TEMPO_S3_SECRET_KEY:supersecret}
      insecure: ${TEMPO_S3_INSECURE:false}
      tls_insecure_skip_verify: true
