
## @param architecture Redis&reg; architecture. Allowed values: `standalone` or `replication`
##
architecture: standalone

auth:
  enabled: true
  existingSecret: redis-credentials

commonConfiguration: |-
  appendonly yes
  maxmemory 64mb
  maxmemory-policy allkeys-lru
  save ""

master:
  podAnnotations:
    logs.agent.grafana.com/scrape: "true"
    logs.agent.grafana.com/scrub-level: "debug" # Boolean whether or not the level should be dropped from the log message (as it is a label).
