apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: rancher-pushprox
  repo: https://charts.rancher.io
  version: 103.0.0
  releaseName: rancher-pushprox
  namespace: monitoring-system
  includeCRDs: false
  valuesFile: values-k3d-k3s.yaml