apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: rancher-pushprox
  version: 102.0.1
  repo: https://charts.rancher.io
  releaseName: rancher-pushprox
  namespace: monitoring-system
  includeCRDs: false
  valuesFile: values-k3d-k3s.yaml