auth_enabled: false

# -reporting.enabled=false
analytics:
 reporting_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095
  log_level: info

common:
  compactor_address: http://compactor:3100
  path_prefix: /loki
  replication_factor: 1
  storage:
    s3:
      bucketnames: loki-data
      endpoint: ${LOKI_S3_ENDPOINT:-minio:9000}
      access_key_id: ${LOKI_S3_ACCESS_KEY_ID:-lgtmp}
      secret_access_key: ${LOKI_S3_SECRET_ACCESS_KEY:-supersecret}
      insecure: ${LOKI_S3_INSECURE:-true}
      s3forcepathstyle: true
      http_config:
        insecure_skip_verify: true

compactor:
  shared_store: s3

memberlist:
  join_members:
  - loki-memberlist:7946

frontend:
  scheduler_address: query-scheduler:9095
  tail_proxy_url: http://querier:3100
frontend_worker:
  scheduler_address: query-scheduler:9095

ruler:
  storage:
    s3:
      bucketnames: loki-ruler

schema_config:
  configs:
  - from: "2023-08-01"
    index:
      period: 24h
      prefix: loki_index_
    object_store: s3
    store: tsdb
    schema: v12

chunk_store_config:
  chunk_cache_config:
    embedded_cache:
      enabled: true

query_range:
  align_queries_with_step: true
  cache_results: true
  max_retries: 5
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        ttl: 1h
