---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: gateway
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
          limits:
            cpu: 999m
            memory: 1Gi
        imagePullPolicy: IfNotPresent
        env:
        - name: NGINX_ENVSUBST_OUTPUT_DIR
          value: /etc/nginx
        envFrom:
        - configMapRef:
            name: nginx-env
        ports:
        - name: http-mimir
          containerPort: 8080
        - name: http-loki
          containerPort: 3100
        - name: http-pyroscope
          containerPort: 4040
        - name: http-tempo
          containerPort: 3200
        - name: grpc-otlp-tempo
          containerPort: 4317
        - name: http-otlp-tempo
          containerPort: 4318
        volumeMounts:
        - name: templates
          mountPath: /etc/nginx/templates
      terminationGracePeriodSeconds: 30
      volumes:
      - name: templates
        projected:
          sources:
          - configMap:
              name: nginx-conf
          - configMap:
              name: nginx-templates
