---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: gateway
  labels:
    app: nginx
spec:
  ports:
  - name: http-mimir
    port: 8080
  - name: http-loki
    port: 3100
  - name: http-tempo
    port: 3200
  - name: http-pyroscope
    port: 4040
  selector:
    app: nginx