---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    grafana_datasource: "1"
  name: grafana-datasources-mimir
  namespace: monitoring-system
data:
  datasources.yaml: |
    apiVersion: 1

    deleteDatasources:
    - name: Metrics
      uid: metrics

    datasources:
    # Mimir for metrics
    - name: Metrics
      type: prometheus
      uid: metrics
      access: proxy
      url: http://nginx.monitoring-system:8080/prometheus
      basicAuth: false
      isDefault: true
      version: 1
      editable: true
