# ============================================================================ #
#                  Read-Write Mode - Metrics
# ============================================================================ #

# ----------------------------------------------------
# apiVersion and kind of Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Notice: Read-Write deployment mode is experimental.
# https://grafana.com/docs/mimir/latest/references/architecture/deployment-modes/#read-write-mode

resources:
- ../../common/grafana-agent
- mimir

secretGenerator:
- name: mimir-env
  namespace: monitoring-system
  literals:
  - MIMIR_S3_SECRET_ACCESS_KEY=VD538OYxSEiGD4I9mmFfqFMCGq1vIiGm

configMapGenerator:
- name: agent-config
  namespace: monitoring-system
  behavior: replace
  files:
  - configs/config.river

- name: mimir-config
  namespace: monitoring-system
  files:
  - configs/mimir.yaml
  - configs/runtime.yaml
  - alertmanager_fallback_config.yaml=configs/alertmanager-fallback-config.yaml

# Update Mimir Read-Write Mode endpoint in gateway
- name: nginx-env
  namespace: gateway
  options:
    disableNameSuffixHash: true
  literals:
  - MIMIR_DISTRIBUTOR_HOST=mimir-write.monitoring-system.svc.cluster.local
  - MIMIR_QUERY_FRONTEND_HOST=mimir-read.monitoring-system.svc.cluster.local
  - MIMIR_ALERT_MANAGER_HOST=mimir-backend.monitoring-system.svc.cluster.local
  - MIMIR_RULER_HOST=mimir-backend.monitoring-system.svc.cluster.local
  - MIMIR_COMPACTOR_HOST=mimir-backend.monitoring-system.svc.cluster.local
