# ============================================================================ #
#                  Read-Write Mode - Metrics
# ============================================================================ #

# ----------------------------------------------------
# apiVersion and kind of Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Notice: Read-Write deployment mode is experimental.
# https://grafana.com/docs/mimir/latest/references/architecture/deployment-modes/#read-write-mode

resources:
- mimir/gossip-ring-headless-svc.yaml
- mimir/mimir-backend-dep.yaml
- mimir/mimir-backend-svc.yaml
- mimir/mimir-backend-servicemonitor.yaml
- mimir/mimir-read-dep.yaml
- mimir/mimir-read-svc.yaml
- mimir/mimir-read-servicemonitor.yaml
- mimir/mimir-write-dep.yaml
- mimir/mimir-write-svc.yaml
- mimir/mimir-write-servicemonitor.yaml

images:
- name: grafana/mimir
  newTag: 2.11.0

secretGenerator:
- name: mimir-env
  namespace: monitoring-system
  literals:
  - MIMIR_S3_SECRET_ACCESS_KEY=VD538OYxSEiGD4I9mmFfqFMCGq1vIiGm

configMapGenerator:
- name: grafana-datasources
  namespace: monitoring-system
  options:
    disableNameSuffixHash: true
    labels:
      grafana_datasource: "1"
  files:
  - datasources.yaml=configs/grafana-datasources-mimir.yaml

- name: mimir-config
  namespace: monitoring-system
  files:
  - configs/mimir.yaml
- name: runtime-config
  namespace: monitoring-system
  files:
  - configs/runtime.yaml

# replace nginx-templates and nginx-env configMap
- name: nginx-templates
  namespace: gateway
  options:
    disableNameSuffixHash: true
  files:
  - configs/gateway_mimir.conf.template
- name: nginx-env
  namespace: gateway
  options:
    disableNameSuffixHash: true
  # We need to fully set all variables because nginx envsubst does not support default values.
  # https://github.com/nginxinc/docker-nginx/issues/592
  literals:
  - MIMIR_DISTRIBUTOR_HOST=mimir-write.monitoring-system.svc.cluster.local
  - MIMIR_QUERY_FRONTEND_HOST=mimir-read.monitoring-system.svc.cluster.local
  - MIMIR_ALERT_MANAGER_HOST=mimir-backend.monitoring-system.svc.cluster.local
  - MIMIR_RULER_HOST=mimir-backend.monitoring-system.svc.cluster.local
  - MIMIR_COMPACTOR_HOST=mimir-backend.monitoring-system.svc.cluster.local
