---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    grafana_datasource: "1"
  name: grafana-datasources-pyroscope
  namespace: monitoring-system
data:
  datasources.yaml: |
    apiVersion: 1

    datasources:
    # Pyroscope for profiles
    - name: Pyroscope
      type: grafana-pyroscope-datasource
      uid: pyroscope
      access: proxy
      orgId: 1
      url: http://pyroscope.profiles-system:4040
      basicAuth: false
      isDefault: true
      version: 1
      editable: true
