# ============================================================================ #
#                  Monolithic Mode - Profiles
# ============================================================================ #

# ----------------------------------------------------
# apiVersion and kind of Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- pyroscope

configMapGenerator:
- name: agent-config
  namespace: monitoring-system
  options:
    disableNameSuffixHash: true
  files:
  - configs/config.river

- name: grafana-datasources
  namespace: monitoring-system
  options:
    labels:
      grafana_datasource: "1"
  files:
  - datasources.yaml=configs/grafana-datasources-pyroscope.yaml
