# ----------------------------------------------------
# apiVersion and kind of Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: true
  pairs:
    team: team-infra

resources:
- grafana-agent/k8s-all-in-one.yaml
- pyroscope/k8s-all-in-one.yaml
- grafana-datasources-pyroscope.yaml
