# ============================================================================ #
#                  Monolithic Mode - Profiles
# ============================================================================ #

# ----------------------------------------------------
# apiVersion and kind of Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../common/alloy
- pyroscope

# optional
- ../metrics/mimir

configMapGenerator:
- name: alloy-config
  namespace: monitoring-system
  behavior: replace
  files:
  - config.alloy=profiles.alloy
