# ----------------------------------------------------
# apiVersion and kind of Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- pyroscope/k8s-all-in-one.yaml

secretGenerator:
- name: agent-env
  namespace: monitoring-system
  options:
    disableNameSuffixHash: true
  literals:
  - CLUSTER=k3d-k3s-codelab
  - PROFILES_ENDPOINT=http://nginx.gateway.svc.cluster.local:4040

# https://grafana.com/docs/pyroscope/latest/configure-server/reference-configuration-parameters/#s3_storage_backend
- name: pyroscope-env
  namespace: profiles-system
  literals:
  - PYROSCOPE_STORAGE_S3_ENDPOINT=minio.minio-system.svc.cluster.local:443
  - PYROSCOPE_STORAGE_S3_ACCESS_KEY_ID=lgtmp
  - PYROSCOPE_STORAGE_S3_SECRET_ACCESS_KEY=VD538OYxSEiGD4I9mmFfqFMCGq1vIiGm

configMapGenerator:
- name: pyroscope-config
  namespace: profiles-system
  options:
    disableNameSuffixHash: true
  behavior: replace
  files:
  - config.yaml=configs/pyroscope.yaml
