# ----------------------------------------------------
# apiVersion and kind of Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: true
  pairs:
    team: team-infra

resources:
- namespace.yaml
- pyroscope/k8s-all-in-one.yaml
- grafana-datasources-pyroscope.yaml

secretGenerator:
- name: agent-env
  namespace: monitoring-system
  options:
    disableNameSuffixHash: true
  literals:
  - CLUSTER=k3d-k3s-codelab
  - PROFILES_ENDPOINT=http://pyroscope.profiles-system:4040
