---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    grafana_datasource: "1"
  name: grafana-datasources-tempo
  namespace: monitoring-system
data:
  datasources.yaml: |
    apiVersion: 1

    deleteDatasources:
    - name: Traces
      uid: traces

    datasources:
    # Traces for traces
    - name: Traces
      type: tempo
      uid: traces
      access: proxy
      url: http://tempo.tracing-system.svc.cluster.local:3100
      basicAuth: false
      isDefault: true
      version: 1
      editable: true
