# ============================================================================ #
#                  Monolithic Mode - Traces
# ============================================================================ #

# ----------------------------------------------------
# apiVersion and kind of Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../common/grafana-agent
- tempo

# optional
- ../metrics/mimir

configMapGenerator:
- name: agent-config
  namespace: monitoring-system
  behavior: replace
  files:
  - configs/config.river

# Update Tempo Monolithic Mode endpoint in gateway
- name: nginx-templates
  namespace: gateway
  options:
    disableNameSuffixHash: true
  files:
  - gateway_tempo.conf.template=configs/gateway_tempo.conf
  - gateway_mimir.conf.template=configs/gateway_mimir.conf
