# ----------------------------------------------------
# apiVersion and kind of Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- tempo/k8s-all-in-one.yaml
- configs/grafana-datasources-tempo.yaml # change default datasources

secretGenerator:
- name: grafana-env
  namespace: monitoring-system
  options:
    disableNameSuffixHash: true
  literals:
  - NAMESPACE=monitoring-system
  - GF_LOG_LEVEL=warn
  - GF_TRACING_OPENTELEMETRY_OTLP_ADDRESS=grafana-agent.monitoring-system:4317
  - GF_TRACING_OPENTELEMETRY_CUSTOM_ATTRIBUTES=namespace:monitoring-system

- name: tempo-env
  namespace: tracing-system
  literals:
  - TEMPO_S3_ENDPOINT=minio.minio-system.svc:443
  - TEMPO_S3_ACCESS_KEY=lgtmp
  - TEMPO_S3_SECRET_KEY=VD538OYxSEiGD4I9mmFfqFMCGq1vIiGm

configMapGenerator:
- name: tempo
  namespace: tracing-system
  behavior: replace
  files:
  - configs/tempo.yaml
  - configs/overrides.yaml

# replace nginx-templates and nginx-env configMap
- name: nginx-templates
  namespace: gateway
  options:
    disableNameSuffixHash: true
  files:
  - configs/gateway_tempo.conf.template
- name: nginx-env
  namespace: gateway
  options:
    disableNameSuffixHash: true
  # We need to fully set all variables because nginx envsubst does not support default values.
  # https://github.com/nginxinc/docker-nginx/issues/592
  literals:
  - TEMPO_DISTRIBUTOR_HOST=tempo.tracing-system.svc.cluster.local
  - TEMPO_INGESTER_HOST=tempo.tracing-system.svc.cluster.local
  - TEMPO_QUERY_FRONTEND_HOST=tempo.tracing-system.svc.cluster.local
  - TEMPO_COMPACTOR_HOST=tempo.tracing-system.svc.cluster.local
