apiVersion: 1

deleteDatasources:
- name: Metrics
  uid: metrics

datasources:
# Mimir for metrics
- name: Metrics
  type: prometheus
  uid: metrics
  access: proxy
  url: http://nginx.gateway.svc.cluster.local:8080/prometheus
  basicAuth: false
  isDefault: true
  version: 1
  editable: true
