# ----------------------------------------------------
# apiVersion and kind of Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# This can improve cloning a large repository, or over a slow network.
# https://github.com/kubernetes-sigs/kustomize/commit/24a64bdee32602b6756608d4c24da28486461199
- github.com/qclaogui/cortex-kustomize/deploy/base/mimir?ref=main&submodules=false&timeout=2m30s
- configs/add-sm-alertmanager.yaml
- configs/add-sm-compactor.yaml
- configs/add-sm-distributor.yaml
- configs/add-sm-ingester.yaml
- configs/add-sm-minio.yaml
- configs/add-sm-overrides-exporter.yaml
- configs/add-sm-querier.yaml
- configs/add-sm-query-frontend.yaml
- configs/add-sm-query-scheduler.yaml
- configs/add-sm-ruler.yaml
- configs/add-sm-store-gateway.yaml

secretGenerator:
- name: agent-env
  namespace: monitoring-system
  options:
    disableNameSuffixHash: true
  literals:
  - CLUSTER=k3d-k3s-codelab
  - METRICS_ENDPOINT=http://nginx.gateway.svc.cluster.local:8080

- name: mimir-env
  namespace: monitoring-system
  behavior: replace
  literals:
  - MIMIR_S3_SECRET_ACCESS_KEY=VD538OYxSEiGD4I9mmFfqFMCGq1vIiGm


configMapGenerator:
- name: runtime-config
  namespace: monitoring-system
  behavior: merge
  files:
  - configs/runtime.yaml
- name: mimir-config
  namespace: monitoring-system
  behavior: replace
  files:
  - configs/mimir.yaml
  - configs/alertmanager-fallback-config.yaml

- name: nginx-env
  namespace: gateway
  options:
    disableNameSuffixHash: true
  # We need to fully set all variables because nginx envsubst does not support default values.
  # https://github.com/nginxinc/docker-nginx/issues/592
  envs:
  - default.env
  literals:
  - MIMIR_DISTRIBUTOR_HOST=distributor.monitoring-system.svc.cluster.local
  - MIMIR_QUERY_FRONTEND_HOST=query-frontend.monitoring-system.svc.cluster.local
  - MIMIR_ALERT_MANAGER_HOST=alertmanager-headless.monitoring-system.svc.cluster.local
  - MIMIR_RULER_HOST=ruler.monitoring-system.svc.cluster.local
  - MIMIR_COMPACTOR_HOST=compactor.monitoring-system.svc.cluster.local
