# ----------------------------------------------------
# apiVersion and kind of Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring-system

labels:
- includeSelectors: true
  pairs:
    team: team-infra

resources:
# This can improve cloning a large repository, or over a slow network.
# https://github.com/kubernetes-sigs/kustomize/commit/24a64bdee32602b6756608d4c24da28486461199
- github.com/qclaogui/cortex-kustomize/deploy/base/mimir?ref=main&submodules=false&timeout=2m30s
- namespace.yaml
- grafana-agent/k8s-all-in-one.yaml
- prometheus-blackbox-exporter/k8s-all-in-one.yaml
- prometheus-node-exporter/k8s-all-in-one.yaml

# patches:
# - path: patch-nginx-svc.yaml

images:
- name: grafana/mimir
  newTag: 2.10.3
- name: docker.io/grafana/agent
  newTag: v0.37.4
- name: quay.io/kiwigrid/k8s-sidecar
  newTag: 1.25.2
- name: docker.io/jimmidyson/configmap-reload
  newTag: v0.8.0

replicas:
- count: 2
  name: ingester

# https://kubernetes.io/docs/concepts/configuration/configmap/#configmap-immutable
generatorOptions:
  immutable: true

# secretGenerator:
# # # just use mimir.yaml in base
# # - name: mimir-config
# #   behavior: replace
# #   files:
# #   - configs/mimir.yaml

configMapGenerator:
- name: runtime-config
  behavior: merge
  files:
  - configs/runtime.yaml

- name: nginx-env
  behavior: merge
  literals:
  - DISTRIBUTOR_HOST=distributor.monitoring-system.svc.cluster.local
  - ALERT_MANAGER_HOST=alertmanager-headless.monitoring-system.svc.cluster.local
  - RULER_HOST=ruler.monitoring-system.svc.cluster.local
  - QUERY_FRONTEND_HOST=query-frontend.monitoring-system.svc.cluster.local
  - COMPACTOR_HOST=compactor.monitoring-system.svc.cluster.local
