# ----------------------------------------------------
# apiVersion and kind of Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- mimir-distributed/k8s-all-in-one.yaml

secretGenerator:
- name: agent-env
  namespace: monitoring-system
  options:
    disableNameSuffixHash: true
  literals:
  - CLUSTER=k3d-k3s-codelab
  - METRICS_ENDPOINT=http://nginx.gateway.svc.cluster.local:8080

- name: mimir-distributed-env
  namespace: monitoring-system
  literals:
  - MIMIR_S3_SECRET_ACCESS_KEY=VD538OYxSEiGD4I9mmFfqFMCGq1vIiGm


configMapGenerator:
- name: mimir-distributed-runtime
  namespace: monitoring-system
  behavior: replace
  files:
  - configs/runtime.yaml
- name: mimir-distributed-config
  namespace: monitoring-system
  behavior: replace
  files:
  - mimir.yaml=configs/mimir-distributed.yaml
- name: mimir-distributed-alertmanager-fallback-config
  namespace: monitoring-system
  behavior: replace
  files:
  - alertmanager_fallback_config.yaml=configs/alertmanager-fallback-config.yaml

# replace nginx-templates and nginx-env configMap
- name: nginx-templates
  namespace: gateway
  options:
    disableNameSuffixHash: true
  files:
  - configs/gateway_mimir.conf.template
- name: nginx-env
  namespace: gateway
  options:
    disableNameSuffixHash: true
  # We need to fully set all variables because nginx envsubst does not support default values.
  # https://github.com/nginxinc/docker-nginx/issues/592
  literals:
  - MIMIR_DISTRIBUTOR_HOST=mimir-distributed-distributor-headless.monitoring-system.svc.cluster.local
  - MIMIR_QUERY_FRONTEND_HOST=mimir-distributed-query-frontend.monitoring-system.svc.cluster.local
  - MIMIR_ALERT_MANAGER_HOST=mimir-distributed-alertmanager-headless.monitoring-system.svc.cluster.local
  - MIMIR_RULER_HOST=mimir-distributed-ruler.monitoring-system.svc.cluster.local
  - MIMIR_COMPACTOR_HOST=mimir-distributed-compactor.monitoring-system.svc.cluster.local
