crds:
  create: false
configReloader:
  enabled: false
alloy:
  enableReporting: false
  configMap:
    create: false
    name: alloy-config
    key: config.alloy
  clustering:
    enabled: true
  stabilityLevel: experimental
  # storagePath: /tmp/alloy
  envFrom:
  - secretRef:
      name: alloy-env
      optional: true
  mounts:
    # TODO(qc) remove this by Alloy import.git
    extra:
    - name: modules-kubernetes-metrics
      mountPath: /etc/alloy/modules/kubernetes/metrics
    - name: modules-kubernetes-integrations
      mountPath: /etc/alloy/modules/kubernetes/integrations
    - name: modules-kubernetes-logs
      mountPath: /etc/alloy/modules/kubernetes/logs
    - name: modules-kubernetes-traces
      mountPath: /etc/alloy/modules/kubernetes/traces
    - name: modules-kubernetes-profiles
      mountPath: /etc/alloy/modules/kubernetes/profiles
  extraPorts:
  - name: "grpc-otlp"
    port: 4317
    targetPort: 4317
    protocol: "TCP"
  - name: "http-otlp"
    port: 4318
    targetPort: 4318
    protocol: "TCP"
  - name: "zipkin"
    port: 9411
    targetPort: 9411
    protocol: "TCP"
  - name: jaeger-compact
    port: 6831
    protocol: UDP
    targetPort: 6831

serviceMonitor:
  enabled: true

ingress:
  enabled: true
  faroPort: 12345
  hosts:
  - alloy.localhost

controller:
  type: statefulset
  enableStatefulSetAutoDeletePVC: true
  replicas: 1
  volumes:
    extra:
    - name: modules-kubernetes-metrics
      configMap:
        name: alloy-modules-kubernetes-metrics
    - name: modules-kubernetes-integrations
      configMap:
        name: alloy-modules-kubernetes-integrations
    - name: modules-kubernetes-logs
      configMap:
        name: alloy-modules-kubernetes-logs
    - name: modules-kubernetes-traces
      configMap:
        name: alloy-modules-kubernetes-traces
    - name: modules-kubernetes-profiles
      configMap:
        name: alloy-modules-kubernetes-profiles
  podAnnotations:
    # https://github.com/grafana/agent-modules/tree/main/modules/kubernetes
    logs.agent.grafana.com/scrape: "true"
    logs.agent.grafana.com/scrub-level: "debug" # Boolean whether or not the level should be dropped from the log message (as it is a label).
    # logs.agent.grafana.com/tenant: ".*"       # Allow a pod to override the tenant for its logs.
    pyroscope.io/service_name: alloy
    profiles.grafana.com/memory.scrape: "false"
    profiles.grafana.com/memory.port_name: "http-metrics"
    profiles.grafana.com/cpu.scrape: "false"
    profiles.grafana.com/cpu.port_name: "http-metrics"
    profiles.grafana.com/goroutine.scrape: "false"
    profiles.grafana.com/goroutine.port_name: "http-metrics"
  nodeSelector:
    kubernetes.io/os: linux