apiVersion: 1

datasources:
# Mimir for metrics
- name: Metrics
  type: prometheus
  uid: metrics
  access: proxy
  orgId: 1
  url: http://nginx:8080/prometheus
  basicAuth: false
  isDefault: true
  version: 1
  editable: true

# Loki for logs
- name: Logs
  type: loki
  access: proxy
  orgId: 1
  uid: logs
  url: http://nginx:3100
  basicAuth: false
  isDefault: false
  version: 1
  editable: true

# Tempo for traces
- name: Traces
  type: tempo
  access: proxy
  orgId: 1
  uid: traces
  url: http://nginx:3200
  basicAuth: false
  isDefault: false
  version: 1
  editable: true
  apiVersion: 1
