version: '3.9'

# ============================================================================ #
#                  Microservices Mode - Metrics
# ============================================================================ #

# Note: 
# include is available in Docker Compose version 2.20 and later, and Docker Desktop version 4.22 and later.
include:
  - path: ../../common/compose-include/minio.yaml
  - path: ../../common/compose-include/agent-collect-metrics.yaml
  - path: ../../common/compose-include/load-mimir-rule.yaml

services:
  gateway:
    depends_on:
      distributor:
        condition: service_healthy
      ruler:
        condition: service_healthy
    image: nginxinc/nginx-unprivileged:1.25-alpine
    volumes:
      - ../../common/config/nginx:/etc/nginx/templates
      - ../../common/config/mimir/gateway_mimir.conf.template:/etc/nginx/templates/gateway_mimir.conf.template
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
      - MIMIR_DISTRIBUTOR_HOST=distributor
      - MIMIR_ALERT_MANAGER_HOST=alertmanager
      - MIMIR_RULER_HOST=ruler
      - MIMIR_QUERY_FRONTEND_HOST=query-frontend
      - MIMIR_COMPACTOR_HOST=compactor
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/ || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "8080"

  distributor:
    depends_on:
      ingester:
        condition: service_started
    image: &mimirImage grafana/mimir:2.11.0
    volumes:
      - ../../common/config/mimir/microservices-mode-metrics.yaml:/etc/mimir.yaml # Note: Mimir use microservices-mode-metrics.yaml
      - ./config/mimir:/etc/mimir
    command:
      - -config.file=/etc/mimir.yaml
      - -target=distributor
      - -config.expand-env=true
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/ready || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      replicas: 2
    networks:
      default:
        aliases:
          - mimir-memberlist

  overrides-exporter:
    image: *mimirImage
    volumes:
      - ../../common/config/mimir/microservices-mode-metrics.yaml:/etc/mimir.yaml # Note: Mimir use microservices-mode-metrics.yaml
      - ./config/mimir:/etc/mimir
    command:
      - -config.file=/etc/mimir.yaml
      - -target=overrides-exporter
      - -config.expand-env=true

  querier:
    depends_on:
      query-scheduler:
        condition: service_healthy
    image: *mimirImage
    volumes:
      - ../../common/config/mimir/microservices-mode-metrics.yaml:/etc/mimir.yaml # Note: Mimir use microservices-mode-metrics.yaml
      - ./config/mimir:/etc/mimir
    command:
      - -config.file=/etc/mimir.yaml
      - -target=querier
      - -config.expand-env=true
    deploy:
      replicas: 2
    networks:
      default:
        aliases:
          - mimir-memberlist

  query-frontend:
    depends_on:
      query-scheduler:
        condition: service_healthy
    image: *mimirImage
    volumes:
      - ../../common/config/mimir/microservices-mode-metrics.yaml:/etc/mimir.yaml # Note: Mimir use microservices-mode-metrics.yaml
      - ./config/mimir:/etc/mimir
    command:
      - -config.file=/etc/mimir.yaml
      - -target=query-frontend
      - -config.expand-env=true

  query-scheduler:
    image: *mimirImage
    volumes:
      - ../../common/config/mimir/microservices-mode-metrics.yaml:/etc/mimir.yaml # Note: Mimir use microservices-mode-metrics.yaml
      - ./config/mimir:/etc/mimir
    command:
      - -config.file=/etc/mimir.yaml
      - -config.expand-env=true
      - -target=query-scheduler
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/ready || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      replicas: 2

  ruler:
    depends_on:
      minio:
        condition: service_healthy
    image: *mimirImage
    volumes:
      - ../../common/config/mimir/microservices-mode-metrics.yaml:/etc/mimir.yaml # Note: Mimir use microservices-mode-metrics.yaml
      - ./config/mimir:/etc/mimir
    command:
      - -config.file=/etc/mimir.yaml
      - -config.expand-env=true
      - -target=ruler
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/ready || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      default:
        aliases:
          - mimir-memberlist

  alertmanager:
    depends_on:
      minio:
        condition: service_healthy
    image: *mimirImage
    volumes:
      - ../../common/config/mimir/microservices-mode-metrics.yaml:/etc/mimir.yaml # Note: Mimir use microservices-mode-metrics.yaml
      - ./config/mimir:/etc/mimir
    command:
      - -config.file=/etc/mimir.yaml
      - -config.expand-env=true
      - -target=alertmanager
    networks:
      default:
        aliases:
          - mimir-memberlist

  compactor:
    depends_on:
      minio:
        condition: service_healthy
    image: *mimirImage
    volumes:
      - ../../common/config/mimir/microservices-mode-metrics.yaml:/etc/mimir.yaml # Note: Mimir use microservices-mode-metrics.yaml
      - ./config/mimir:/etc/mimir
    command:
      - -config.file=/etc/mimir.yaml
      - -config.expand-env=true
      - -target=compactor
    networks:
      default:
        aliases:
          - mimir-memberlist

  ingester:
    depends_on:
      minio:
        condition: service_healthy
    image: *mimirImage
    volumes:
      - ../../common/config/mimir/microservices-mode-metrics.yaml:/etc/mimir.yaml # Note: Mimir use microservices-mode-metrics.yaml
      - ./config/mimir:/etc/mimir
    command:
      - -config.file=/etc/mimir.yaml
      - -config.expand-env=true
      - -target=ingester
    ports:
      - "8080"
    deploy:
      replicas: 3
    networks:
      default:
        aliases:
          - mimir-memberlist

  store-gateway:
    depends_on:
      minio:
        condition: service_healthy
    image: *mimirImage
    volumes:
      - ../../common/config/mimir/microservices-mode-metrics.yaml:/etc/mimir.yaml # Note: Mimir use microservices-mode-metrics.yaml
      - ./config/mimir:/etc/mimir
    command:
      - -config.file=/etc/mimir.yaml
      - -config.expand-env=true
      - -target=store-gateway
    networks:
      default:
        aliases:
          - mimir-memberlist

  grafana:
    image: grafana/grafana:10.4.0
    command:
      - --config=/etc/grafana-config/grafana.ini
    volumes:
      - ../../common/config/grafana/grafana.ini:/etc/grafana-config/grafana.ini
      - ../../common/config/grafana/dashboards:/var/lib/grafana/dashboards
      - ../../common/config/grafana/provisioning:/etc/grafana/provisioning
      - ../../common/config/mimir/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml    # load datasources
      - ../../../monitoring-mixins/mimir-mixin/deploy/dashboards_out:/var/lib/grafana/dashboards/mimir-mixin # load dashboards
      - ../../../monitoring-mixins/agent-flow-mixin/deploy/dashboards_out:/var/lib/grafana/dashboards/agent-flow-mixin
      - ../../../monitoring-mixins/go-runtime-mixin/deploy/dashboards_out:/var/lib/grafana/dashboards/go-runtime-mixin
    environment:
      - GF_LOG_LEVEL=error
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-admin_password}
    ports:
      - "3000:3000"
