
services:
  alloy: # override included service alloy entrypoint
    entrypoint:
      - /bin/alloy
      - run
      - /etc/alloy/profiles.alloy # Note: Alloy use profiles.alloy
      - --server.http.listen-addr=0.0.0.0:12345
      - --cluster.enabled=true
      - --cluster.join-addresses=alloy-cluster:12345
      - --disable-reporting=true
      - --stability.level=experimental
      - --storage.path=/var/lib/alloy/data
