version: '3.9'

# ============================================================================ #
#                  Microservices Mode - Profiles
# ============================================================================ #

# Note: 
# include is available in Docker Compose version 2.20 and later, and Docker Desktop version 4.22 and later.
# docs: https://docs.docker.com/compose/multiple-compose-files/include/#include-and-overrides
include:
  - path: ../../common/compose-include/minio.yaml
  - path: ../../common/compose-include/memcached.yaml
  - path: ../../common/compose-include/mimir.yaml
  - path:
      - ../../common/compose-include/grafana-agent.yaml
      - ./compose.override.yaml  # Microservices Mode services override
  - path: ../../common/compose-include/grafana.yaml

# https://github.com/qclaogui/codelab-monitoring/blob/main/docker-compose/common/config/agent-flow/modules/docker/README.md
x-labels: &profiles-labels
  profiles.agent.grafana.com/cpu.scrape: true
  profiles.agent.grafana.com/memory.scrape: true
  profiles.agent.grafana.com/goroutine.scrape: true

services:
  gateway:
    # https://github.com/qclaogui/codelab-monitoring/blob/main/docker-compose/common/config/agent-flow/modules/docker/README.md
    labels:
      metrics.agent.grafana.com/scrape: false
    depends_on:
      distributor:
        condition: service_healthy
    image: ${NGINX_IMAGE:-docker.io/nginxinc/nginx-unprivileged:1.25-alpine}
    restart: always
    volumes:
      - ../../common/config/nginx/10-default-lgtmp.envsh:/docker-entrypoint.d/10-default-lgtmp.envsh
      - ../../common/config/nginx/nginx.conf:/etc/nginx/templates/nginx.conf.template
      - ../../common/config/pyroscope/gateway_pyroscope.conf:/etc/nginx/templates/gateway_pyroscope.conf.template
      - ../../common/config/mimir/gateway_mimir.conf:/etc/nginx/templates/gateway_mimir.conf.template
    environment:
      - PYROSCOPE_DISTRIBUTOR_HOST=distributor
      - PYROSCOPE_QUERY_FRONTEND_HOST=query-frontend
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:4040/ || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - "34040:4040"

  distributor:
    labels:
      <<: *profiles-labels
      profiles.agent.grafana.com/service_name: pyroscope-distributor
    depends_on:
      ingester:
        condition: service_started
    image: &pyroscopeImage ${PYROSCOPE_IMAGE:-docker.io/grafana/pyroscope:1.5.0}
    volumes:
      - ../../common/config/pyroscope:/etc/pyroscope
    command:
      - -config.file=/etc/pyroscope/microservices-mode-profiles.yaml
      - -target=distributor
      - -config.expand-env=true
      - -memberlist.cluster-label=profiles-system
      - -memberlist.join=pyroscope-memberlist:7946
      # - -runtime-config.file=/etc/pyroscope/overrides.yaml
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:4040/ready || exit 1" ]
      interval: 15s
      timeout: 10s
      retries: 10
    networks:
      default:
        aliases:
          - pyroscope-memberlist

  ingester:
    labels:
      <<: *profiles-labels
      profiles.agent.grafana.com/service_name: pyroscope-ingester
    depends_on:
      minio:
        condition: service_healthy
    image: *pyroscopeImage
    volumes:
      - ../../common/config/pyroscope:/etc/pyroscope
    command:
      - -config.file=/etc/pyroscope/microservices-mode-profiles.yaml
      - -target=ingester
      - -config.expand-env=true
      - -memberlist.cluster-label=profiles-system
      - -memberlist.join=pyroscope-memberlist:7946
    deploy:
      replicas: 3
    networks:
      default:
        aliases:
          - pyroscope-memberlist

  compactor:
    labels:
      <<: *profiles-labels
      profiles.agent.grafana.com/service_name: pyroscope-compactor
    depends_on:
      minio:
        condition: service_healthy
    image: *pyroscopeImage
    volumes:
      - ../../common/config/pyroscope:/etc/pyroscope
    command:
      - -config.file=/etc/pyroscope/microservices-mode-profiles.yaml
      - -target=compactor
      - -config.expand-env=true
      - -memberlist.cluster-label=profiles-system
      - -memberlist.join=pyroscope-memberlist:7946
    deploy:
      replicas: 1
    networks:
      default:
        aliases:
          - pyroscope-memberlist

  query-frontend:
    labels:
      <<: *profiles-labels
      profiles.agent.grafana.com/service_name: pyroscope-query-frontend
    depends_on:
      minio:
        condition: service_healthy
    image: *pyroscopeImage
    volumes:
      - ../../common/config/pyroscope:/etc/pyroscope
    command:
      - -config.file=/etc/pyroscope/microservices-mode-profiles.yaml
      - -target=query-frontend
      - -config.expand-env=true
      - -memberlist.cluster-label=profiles-system
      - -memberlist.join=pyroscope-memberlist:7946
    networks:
      default:
        aliases:
          - pyroscope-memberlist

  querier:
    labels:
      <<: *profiles-labels
      profiles.agent.grafana.com/service_name: pyroscope-querier
    depends_on:
      minio:
        condition: service_healthy
      query-frontend:
        condition: service_started
    image: *pyroscopeImage
    volumes:
      - ../../common/config/pyroscope:/etc/pyroscope
    command:
      - -config.file=/etc/pyroscope/microservices-mode-profiles.yaml
      - -target=querier
      - -config.expand-env=true
      - -memberlist.cluster-label=profiles-system
      - -memberlist.join=pyroscope-memberlist:7946
      - -store-gateway.sharding-ring.replication-factor=1
    networks:
      default:
        aliases:
          - pyroscope-memberlist
  
  query-scheduler:
    labels:
      <<: *profiles-labels
      profiles.agent.grafana.com/service_name: pyroscope-query-scheduler
    depends_on:
      minio:
        condition: service_healthy
    image: *pyroscopeImage
    volumes:
      - ../../common/config/pyroscope:/etc/pyroscope
    command:
      - -config.file=/etc/pyroscope/microservices-mode-profiles.yaml
      - -target=query-scheduler
      - -config.expand-env=true
      - -memberlist.cluster-label=profiles-system
      - -memberlist.join=pyroscope-memberlist:7946
    networks:
      default:
        aliases:
          - pyroscope-memberlist

  store-gateway:
    labels:
      <<: *profiles-labels
      profiles.agent.grafana.com/service_name: pyroscope-store-gateway
    depends_on:
      minio:
        condition: service_healthy
    image: *pyroscopeImage
    volumes:
      - ../../common/config/pyroscope:/etc/pyroscope
    command:
      - -config.file=/etc/pyroscope/microservices-mode-profiles.yaml
      - -target=store-gateway
      - -config.expand-env=true
      - -memberlist.cluster-label=profiles-system
      - -memberlist.join=pyroscope-memberlist:7946
      - -store-gateway.sharding-ring.replication-factor=1
    networks:
      default:
        aliases:
          - pyroscope-memberlist
