
services:
  # override included service mimirtool for rules and alerts pre-provisioning
  mimirtool:
    volumes:
      - ../../../monitoring-mixins/pyroscope-mixin/deploy/pyroscope-mixin-rules.yaml:/rules/pyroscope-mixin-rules.yaml
