---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: mimir-backend
  name: mimir-backend
spec:
  ports:
  - name: http-metrics
    port: 8080
  - name: grpc-distribut
    port: 9095
  selector:
    app.kubernetes.io/component: mimir-backend
