---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: mimir-backend
  name: mimir-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/component: mimir-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/component: mimir-backend
    spec:
      containers:
      - args:
        - -target=backend
        - -config.expand-env=true
        - -config.file=/etc/mimir/mimir.yaml
        - -memberlist.bind-addr=$(POD_IP)
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        envFrom:
        - secretRef:
            name: mimir-env
        image: docker.io/grafana/mimir
        imagePullPolicy: IfNotPresent
        name: mimir-backend
        resources:
          requests:
            cpu: 10m
            memory: 55Mi
          limits:
            cpu: 999m
            memory: 1Gi
        ports:
        - containerPort: 8080
          name: http-metrics
        - containerPort: 9095
          name: grpc-distribut
        - containerPort: 7946
          name: http-memberlist
        readinessProbe:
          httpGet:
            path: /ready
            port: http-metrics
        volumeMounts:
        - mountPath: /etc/mimir
          name: mimir-config
        - mountPath: /var/mimir
          name: runtime-config
      terminationGracePeriodSeconds: 60
      volumes:
      - name: mimir-config
        configMap:
          name: mimir-config
      - name: runtime-config
        configMap:
          name: runtime-config
