apiVersion: 1

datasources:
# Mimir for metrics
- name: Metrics
  type: prometheus
  uid: metrics
  access: proxy
  url: http://nginx.gateway.svc.cluster.local:8080/prometheus
  basicAuth: false
  isDefault: false
  version: 1
  editable: true

# Loki for logs
- name: Logs
  type: loki
  uid: logs
  access: proxy
  url: http://nginx.gateway.svc.cluster.local:3100
  basicAuth: false
  isDefault: false
  version: 1
  editable: true

# Tempo for traces
- name: Traces
  type: tempo
  access: proxy
  uid: traces
  url: http://nginx.gateway.svc.cluster.local:3200
  basicAuth: false
  isDefault: false
  version: 1
  editable: true
  apiVersion: 1

# Pyroscope for profiles
- name: Profiles
  type: grafana-pyroscope-datasource
  uid: profiles
  access: proxy
  url: http://nginx.gateway.svc.cluster.local:4040
  basicAuth: false
  isDefault: false
  version: 1
  editable: true
