apiVersion: 1

deleteDatasources:
- name: Metrics
  uid: metrics
- name: Logs
  uid: logs

datasources:
# Mimir for metrics
- name: Metrics
  type: prometheus
  uid: metrics
  access: proxy
  url: http://nginx.gateway.svc.cluster.local:8080/prometheus
  basicAuth: false
  isDefault: true
  version: 1
  editable: true

# Loki for logs
- name: Logs
  type: loki
  uid: logs
  access: proxy
  url: http://nginx.gateway.svc.cluster.local:3100
  basicAuth: false
  isDefault: true
  version: 1
  editable: true
