# ============================================================================ #
#                  Microservices Mode - Traces
# ============================================================================ #

# ----------------------------------------------------
# apiVersion and kind of Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- tempo-distributed
- ../../monolithic-mode/metrics

secretGenerator:
- name: grafana-env
  namespace: monitoring-system
  options:
    disableNameSuffixHash: true
  literals:
  - NAMESPACE=monitoring-system
  - GF_LOG_LEVEL=warn
  - GF_TRACING_OPENTELEMETRY_OTLP_ADDRESS=grafana-agent.monitoring-system:4317
  - GF_TRACING_OPENTELEMETRY_CUSTOM_ATTRIBUTES=namespace:monitoring-system
  - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor tracesEmbeddedFlameGraph traceqlSearch correlations metricsSummary traceToMetrics traceToProfiles

- name: tempo-distributed-env
  namespace: tracing-system
  literals:
  - TEMPO_S3_SECRET_KEY=VD538OYxSEiGD4I9mmFfqFMCGq1vIiGm
  - JAEGER_SERVICE_NAME=tempo
  - JAEGER_AGENT_HOST=agent
  - JAEGER_AGENT_PORT=6831
  - JAEGER_SAMPLER_TYPE=const
  - JAEGER_SAMPLER_PARAM=1

- name: mimir-env
  namespace: monitoring-system
  behavior: replace
  literals:
  - MIMIR_S3_SECRET_ACCESS_KEY=VD538OYxSEiGD4I9mmFfqFMCGq1vIiGm
  - JAEGER_SERVICE_NAME=mimir
  - JAEGER_AGENT_HOST=agent
  - JAEGER_AGENT_PORT=6831
  - JAEGER_SAMPLER_TYPE=const
  - JAEGER_SAMPLER_PARAM=1

configMapGenerator:
- name: grafana-datasources
  namespace: monitoring-system
  options:
    disableNameSuffixHash: true
    labels:
      grafana_datasource: "1"
  files:
  - datasources.yaml=configs/grafana-datasources-tempo.yaml

- name: agent-config
  namespace: monitoring-system
  behavior: replace
  options:
    disableNameSuffixHash: true
  files:
  - configs/config.river


- name: tempo-distributed-config
  namespace: tracing-system
  behavior: replace
  files:
  - tempo.yaml=configs/tempo-distributed.yaml
- name: tempo-distributed-runtime
  namespace: tracing-system
  behavior: replace
  files:
  - configs/overrides.yaml

- name: mimir-config
  namespace: monitoring-system
  behavior: replace
  files:
  - configs/mimir.yaml
- name: runtime-config
  namespace: monitoring-system
  behavior: replace
  files:
  - runtime.yaml=configs/mimir-runtime.yaml

# replace nginx-templates and nginx-env configMap
- name: nginx-templates
  namespace: gateway
  options:
    disableNameSuffixHash: true
  files:
  - configs/gateway_tempo.conf.template
  - configs/gateway_mimir.conf.template
- name: nginx-env
  namespace: gateway
  options:
    disableNameSuffixHash: true
  # We need to fully set all variables because nginx envsubst does not support default values.
  # https://github.com/nginxinc/docker-nginx/issues/592
  literals:
  - TEMPO_DISTRIBUTOR_HOST=tempo-distributed-distributor.tracing-system.svc.cluster.local
  - TEMPO_INGESTER_HOST=tempo-distributed-ingester.tracing-system.svc.cluster.local
  - TEMPO_QUERY_FRONTEND_HOST=tempo-distributed-query-frontend.tracing-system.svc.cluster.local
  - TEMPO_COMPACTOR_HOST=tempo-distributed-compactor.tracing-system.svc.cluster.local
  - MIMIR_DISTRIBUTOR_HOST=mimir.monitoring-system.svc.cluster.local
  - MIMIR_QUERY_FRONTEND_HOST=mimir.monitoring-system.svc.cluster.local
  - MIMIR_ALERT_MANAGER_HOST=mimir.monitoring-system.svc.cluster.local
  - MIMIR_RULER_HOST=mimir.monitoring-system.svc.cluster.local
  - MIMIR_COMPACTOR_HOST=mimir.monitoring-system.svc.cluster.local
