# config file version
apiVersion: 1

# List of contact points to import or update
# https://grafana.com/docs/grafana/latest/alerting/set-up/provision-alerting-resources/file-provisioning/#provision-contact-points
contactPoints:
  - orgId: 1
    name: cp_wangweifeng
    receivers:
      # - uid: cp_slack_wangweifeng
      #   type: slack
      #   disableResolveMessage: false
      #   settings:
      #     url: ${SLACK_WEBHOOK_URL}
      - uid: cp_email_wangweifeng
        type: email
        disableResolveMessage: false
        settings:
          singleEmail: false
          addresses: me@example.com;you@example.com
