apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring-system

helmCharts:
- name: prometheus-node-exporter
  version: 4.23.2
  repo: https://prometheus-community.github.io/helm-charts
  releaseName: prometheus-node-exporter
  namespace: monitoring-system
  includeCRDs: false
  valuesFile: values-k3d-k3s.yaml