apiVersion: 1

datasources:
# Mimir for metrics
- name: Metrics
  type: prometheus
  uid: metrics
  access: proxy
  orgId: 1
  url: http://mimir:8080/prometheus
  basicAuth: false
  isDefault: false
  version: 1
  editable: true
  jsonData:
    prometheusType: Mimir
    exemplarTraceIdDestinations:
      - name: traceID
        datasourceUid: traces


# Loki for logs
- name: Logs
  type: loki
  access: proxy
  orgId: 1
  uid: logs
  url: http://loki:3100
  basicAuth: false
  isDefault: false
  version: 1
  editable: true
  jsonData:
    derivedFields:
      - datasourceUid: traces
        matcherRegex: "[tT]race_?[iI][dD]\"?[:=]\"?(\\w+)"
        name: traceID
        url: $${__value.raw}


# Tempo for traces
- name: Traces
  type: tempo
  access: proxy
  orgId: 1
  uid: traces
  url: http://tempo:3200
  basicAuth: false
  isDefault: false
  version: 1
  editable: true
  apiVersion: 1
  jsonData:
    lokiSearch:
      datasourceUid: logs
    nodeGraph:
      enabled: true
    serviceMap:
      datasourceUid: metrics
    tracesToMetrics:
      datasourceUid: metrics
    tracesToLogsV2:
      customQuery: false
      datasourceUid: logs


# Pyroscope for profiles
- name: Profiles
  type: phlare
  access: proxy
  orgId: 1
  uid: profiles
  url: http://pyroscope:4040
  basicAuth: false
  isDefault: false
  version: 1
  editable: true
