version: '3.9'

# ============================================================================ #
#                  Monolithic Mode - Profiles
# ============================================================================ #

# Note: 
# include is available in Docker Compose version 2.20 and later, and Docker Desktop version 4.22 and later.
include:
  - path: ../../common/compose-include/minio.yaml
  - path: ../../common/compose-include/memcached.yaml
  - path: ../../common/compose-include/agent-collect-profiles.yaml
  # optional
  - path: ../../common/compose-include/mimir.yaml
  # # for git remote  
  # #   https://github.com/docker/compose/pull/10811
  # #   https://docs.docker.com/engine/reference/commandline/build/#git-repositories
  # # - git@github.com:ndeloof/test.git
  # - https://github.com/qclaogui/codelab-monitoring.git#main:docker-compose/common/compose-include/minio.yaml
  # - https://github.com/qclaogui/codelab-monitoring.git#main:docker-compose/common/compose-include/agent-collect-profiles.yaml

# https://github.com/qclaogui/codelab-monitoring/blob/main/docker-compose/common/config/agent-flow/modules/docker/README.md
x-labels: &profiles-labels
  profiles.agent.grafana.com/cpu.scrape: true
  profiles.agent.grafana.com/memory.scrape: true
  profiles.agent.grafana.com/goroutine.scrape: true
  profiles.agent.grafana.com/block.scrape: true
  profiles.agent.grafana.com/mutex.scrape: true
  profiles.agent.grafana.com/fgprof.scrape: true

services:
  gateway:
    # https://github.com/qclaogui/codelab-monitoring/blob/main/docker-compose/common/config/agent-flow/modules/docker/README.md
    labels:
      metrics.agent.grafana.com/scrape: false
    depends_on:
      pyroscope:
        condition: service_healthy
    image: ${NGINX_IMAGE:-docker.io/nginxinc/nginx-unprivileged:latest}
    volumes:
      - ../../common/config/nginx/10-default-lgtmp.envsh:/docker-entrypoint.d/10-default-lgtmp.envsh
      - ../../common/config/nginx/nginx.conf:/etc/nginx/templates/nginx.conf.template
      - ../../common/config/pyroscope/gateway_pyroscope.conf:/etc/nginx/templates/gateway_pyroscope.conf.template
      - ../../common/config/mimir/gateway_mimir.conf:/etc/nginx/templates/gateway_mimir.conf.template
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:4040/ || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pyroscope:
    depends_on:
      minio:
        condition: service_healthy
    image: ${PYROSCOPE_IMAGE:-docker.io/grafana/pyroscope:latest}
    container_name: pyroscope
    volumes:
      - ../../common/config/pyroscope:/etc/pyroscope
    command:
      - -config.file=/etc/pyroscope/monolithic-mode-profiles.yaml
      - -target=all
      - -config.expand-env=true
      # - -runtime-config.file=/etc/pyroscope/overrides.yaml
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:4040/ready || exit 1" ]
      interval: 15s
      timeout: 10s
      retries: 5
    # expose 34040 port so we can directly access pyroscope inside container
    ports:
      - "34040:4040"

  grafana:
    # https://github.com/qclaogui/codelab-monitoring/blob/main/docker-compose/common/config/agent-flow/modules/docker/README.md
    labels:
      <<: *profiles-labels
      profiles.agent.grafana.com/service_name: grafana
      profiles.agent.grafana.com/port: 6060
      logs.agent.grafana.com/log-format: logfmt
    image: ${GRAFANA_IMAGE:-docker.io/grafana/grafana:latest}
    hostname: grafana
    command:
      - --config=/etc/grafana-config/grafana.ini
    volumes:
      - ../../common/config/grafana/grafana.ini:/etc/grafana-config/grafana.ini
      - ../../common/config/grafana/dashboards:/var/lib/grafana/dashboards
      - ../../common/config/grafana/provisioning:/etc/grafana/provisioning
      - ../../../monitoring-mixins/agent-flow-mixin/deploy/dashboards_out:/var/lib/grafana/dashboards/agent-flow-mixin
      - ../../../monitoring-mixins/go-runtime-mixin/deploy/dashboards_out:/var/lib/grafana/dashboards/go-runtime-mixin
      - ../../../monitoring-mixins/mimir-mixin/deploy/dashboards_out:/var/lib/grafana/dashboards/mimir-mixin
      - ../../../monitoring-mixins/pyroscope-mixin/deploy/dashboards_out:/var/lib/grafana/dashboards/pyroscope-mixin
      - ../../../monitoring-mixins/memcached-mixin/deploy/dashboards_out:/var/lib/grafana/dashboards/memcached-mixin
    environment:
      - GF_LOG_LEVEL=warn
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-admin_password}
      - GF_FEATURE_TOGGLES_ENABLE=flameGraph
      - GF_DIAGNOSTICS_PROFILING_ENABLED=true
      - GF_DIAGNOSTICS_PROFILING_ADDR=0.0.0.0
      - GF_DIAGNOSTICS_PROFILING_PORT=6060
      # - GF_INSTALL_PLUGINS=pyroscope-datasource,pyroscope-panel
    ports:
      - "3000:3000"
