
services:
  grafana-agent: # override included service grafana-agent entrypoint
    entrypoint:
      - /bin/grafana-agent
      - run
      - /etc/agent-config/profiles.river # Note: Agent use profiles.river
      - --server.http.listen-addr=0.0.0.0:12345
      - --cluster.enabled=true
      - --cluster.join-addresses=grafana-agent-cluster:12345
      - --disable-reporting=true
