
services:
  # override included service grafana for dashboards pre-provisioning
  grafana:
    volumes:
      - ../../../monitoring-mixins/pyroscope-mixin/deploy/dashboards_out:/var/lib/grafana/dashboards/pyroscope-mixin
