apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


helmCharts:
- name: kube-prometheus-stack
  version: 55.3.1
  repo: https://prometheus-community.github.io/helm-charts
  releaseName: kube-prometheus-stack
  namespace: monitoring-system
  includeCRDs: false
  valuesFile: values-k3d-k3s.yaml
