crds:
  enabled: false

alertmanager:
  enabled: false

prometheusOperator:
  enabled: false

prometheus:
  enabled: false

grafana:
  enabled: false
  forceDeployDashboards: true
  defaultDashboardsTimezone: browser
  sidecar:
    dashboards:
      multicluster:
        global:
          enabled: true
        etcd:
          enabled: true

nodeExporter:
  operatingSystems:
    darwin:
      enabled: false
