apiVersion: 1

deleteDatasources:
- name: Profiles
  uid: profiles

datasources:
# Pyroscope for profiles
- name: Profiles
  type: grafana-pyroscope-datasource
  uid: profiles
  access: proxy
  url: http://nginx.gateway.svc.cluster.local:4040
  basicAuth: false
  isDefault: true
  version: 1
  editable: true
