analytics:
  reporting_enabled: false

storage:
  backend: s3
  s3:
    bucket_name: pyroscope-data
    endpoint: ${PYROSCOPE_STORAGE_S3_ENDPOINT:minio.minio-system.svc.cluster.local:443}
    access_key_id: ${PYROSCOPE_STORAGE_S3_ACCESS_KEY_ID:lgtmp}
    secret_access_key: ${PYROSCOPE_STORAGE_S3_SECRET_ACCESS_KEY:supersecret}
    insecure: false
    http:
      insecure_skip_verify: true
