version: '3.9'

# ============================================================================ #
#                  Monolithic Mode - Traces
# ============================================================================ #

# Note: 
# include is available in Docker Compose version 2.20 and later, and Docker Desktop version 4.22 and later.
include:
  - path: ../../common/compose-include/minio.yaml
  - path: ../../common/compose-include/agent-collect-traces.yaml
  - path: ../../common/compose-include/load-mimir-rule.yaml
  - path: ../../common/compose-include/load-tempo-rule.yaml

services:
  gateway:
    depends_on:
      tempo:
        condition: service_healthy
    image: nginxinc/nginx-unprivileged:1.25-alpine
    restart: always
    volumes:
      - ../../common/config/nginx:/etc/nginx/templates
      - ../../common/config/tempo/gateway_tempo.conf.template:/etc/nginx/templates/gateway_tempo.conf.template
      - ../../common/config/mimir/gateway_mimir.conf.template:/etc/nginx/templates/gateway_mimir.conf.template
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
      - TEMPO_DISTRIBUTOR_HOST=tempo
      - TEMPO_INGESTER_HOST=tempo
      - TEMPO_QUERY_FRONTEND_HOST=tempo
      - TEMPO_COMPACTOR_HOST=tempo
      - MIMIR_DISTRIBUTOR_HOST=mimir
      - MIMIR_ALERT_MANAGER_HOST=mimir
      - MIMIR_RULER_HOST=mimir
      - MIMIR_QUERY_FRONTEND_HOST=mimir
      - MIMIR_COMPACTOR_HOST=mimir
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3200/ || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  tempo:
    depends_on:
      minio:
        condition: service_started
    image: &tempoImage grafana/tempo:2.4.0
    restart: always
    volumes:
      - ./config/tempo/scalable-single-binary.yaml:/etc/tempo.yaml # Note: Tempo use scalable-single-binary.yaml
    command:
      - -config.file=/etc/tempo.yaml
      - -target=scalable-single-binary
      - -log.level=warn
      - -config.expand-env=true
    environment:
      - JAEGER_AGENT_HOST=agent
      - JAEGER_AGENT_PORT=6831
      - JAEGER_TAGS=app=tempo
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
    # Horizontally scale up support(Monolithic mode)
    # https://grafana.com/docs/tempo/latest/setup/deployment/#scaling-monolithic-mode
    deploy:
      replicas: 1
    networks:
      default:
        aliases:
          - tempo-memberlist

  mimir:
    depends_on:
      minio:
        condition: service_started
    image: grafana/mimir:2.11.0
    volumes:
      - ../../common/config/mimir/monolithic-mode-metrics.yaml:/etc/config.yaml
    command:
      - -config.file=/etc/config.yaml
      - -target=all
      - -config.expand-env=true
      - -log.level=warn
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/ready || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      replicas: 1
    networks:
      default:
        aliases:
          - mimir-memberlist

  grafana:
    depends_on:
      minio:
        condition: service_started
    image: grafana/grafana:10.4.0
    command:
      - --config=/etc/grafana-config/grafana.ini
    volumes:
      - ../../common/config/grafana/grafana.ini:/etc/grafana-config/grafana.ini
      - ../../common/config/grafana/dashboards:/var/lib/grafana/dashboards
      - ../../common/config/grafana/provisioning:/etc/grafana/provisioning
      - ../../common/config/tempo/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml # load datasources
      - ../../../monitoring-mixins/mimir-mixin/deploy/dashboards_out:/var/lib/grafana/dashboards/mimir-mixin
      # - ../../../monitoring-mixins/tempo-mixin/deploy/dashboards_out:/var/lib/grafana/dashboards/tempo-mixin
      - ../../../monitoring-mixins/agent-flow-mixin/deploy/dashboards_out:/var/lib/grafana/dashboards/agent-flow-mixin
      - ../../../monitoring-mixins/go-runtime-mixin/deploy/dashboards_out:/var/lib/grafana/dashboards/go-runtime-mixin
    environment:
      - GF_LOG_LEVEL=warn
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-admin_password}
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor tracesEmbeddedFlameGraph traceqlSearch correlations metricsSummary traceToMetrics traceToProfiles
    ports:
      - "3000:3000"
