apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring-system

helmCharts:
- name: grafana-agent
  version: 0.29.0
  repo: https://grafana.github.io/helm-charts
  releaseName: grafana-agent
  namespace: monitoring-system
  includeCRDs: false
  valuesFile: values-k3d-k3s.yaml

images:
- name: docker.io/grafana/agent
  newTag: v0.38.1

configMapGenerator:
- name: agent-config
  namespace: monitoring-system
  options:
    disableNameSuffixHash: true
  files:
  - configs/config.river

# Agent Modules Config
- name: agent-modules
  namespace: monitoring-system
  files:
  - configs/modules/lgtmp.river
  - configs/modules/logs.river
  - configs/modules/metrics.river
  - configs/modules/profiles.river
  - configs/modules/traces.river
  - configs/modules/integrations.river

# Agent Integrations Config
- name: agent-integrations
  namespace: monitoring-system
  options:
    disableNameSuffixHash: true
  literals:
  - MYSQL_SECRET_NAME=integrations-mysql
  - MEMCACHED_SECRET_NAME=integrations-memcached
  - REDIS_SECRET_NAME=integrations-redis
  files:
  - integrations/mysql.river
  - integrations/memcached.river
  - integrations/redis.river


secretGenerator:
# integrations mysql credentials
- name: integrations-mysql
  namespace: monitoring-system
  options:
    disableNameSuffixHash: true
  literals:
  - mysql-host=mysql.mysql-system.svc.cluster.local
  - mysql-username=lgtmp
  - mysql-password=VD538OYxSEiGD4I9mmFfqFMCGq1vIiGm

# integrations memcached credentials
- name: integrations-memcached
  namespace: monitoring-system
  options:
    disableNameSuffixHash: true
  literals:
  - memcached-address=memcached.memcached-system.svc.cluster.local:11211

# integrations redis credentials
- name: integrations-redis
  namespace: monitoring-system
  options:
    disableNameSuffixHash: true
  literals:
  - redis-addr=redis-master.redis-system.svc.cluster.local:6379
  - redis-password=VD538OYxSEiGD4I9mmFfqFMCGq1vIiGm
