apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring-system

helmCharts:
- name: grafana-agent
  version: 0.29.0
  repo: https://grafana.github.io/helm-charts
  releaseName: grafana-agent
  namespace: monitoring-system
  includeCRDs: false
  valuesFile: values-k3d-k3s.yaml


configMapGenerator:
- name: agent-config
  files:
  - configs/config.river
- name: agent-modules
  files:
  - configs/modules/lgtmp.river
  - configs/modules/logs.river
  - configs/modules/metrics.river
  - configs/modules/profiles.river
  - configs/modules/traces.river

