apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring-system

helmCharts:
- name: grafana-agent
  version: 0.27.2
  repo: https://grafana.github.io/helm-charts
  releaseName: grafana-agent
  namespace: monitoring-system
  includeCRDs: false
  valuesFile: values-k3d-k3s.yaml

images:
- name: docker.io/grafana/agent
  newTag: v0.37.4

configMapGenerator:
- name: agent-config
  files:
  - configs/config.river
- name: agent-modules
  files:
  - configs/modules/lgtmp.river
  - configs/modules/logs.river
  - configs/modules/profiles.river
  - configs/modules/metrics.river
