apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring-system

helmCharts:
- name: grafana-agent
  version: 0.29.0
  repo: https://grafana.github.io/helm-charts
  releaseName: grafana-agent
  namespace: monitoring-system
  includeCRDs: false
  valuesFile: values-k3d-k3s.yaml


configMapGenerator:
- name: agent-config
  files:
  - configs/config.river
- name: agent-modules
  files:
  - configs/modules/lgtmp.river
  - configs/modules/logs.river
  - configs/modules/metrics.river
  - configs/modules/profiles.river
  - configs/modules/traces.river
  - configs/modules/integrations.river

# integrations mysql config
- name: integrations-mysql-config
  namespace: monitoring-system
  options:
    disableNameSuffixHash: true
  files:
  - integrations/mysql/metrics.river

# integrations memcached config
- name: integrations-memcached-config
  namespace: monitoring-system
  options:
    disableNameSuffixHash: true
  files:
  - integrations/memcached/metrics.river

# integrations redis config
- name: integrations-redis-config
  namespace: monitoring-system
  options:
    disableNameSuffixHash: true
  files:
  - integrations/redis/metrics.river


secretGenerator:
# integrations mysql credentials
- name: integrations-mysql-secret
  namespace: monitoring-system
  options:
    disableNameSuffixHash: true
  literals:
  - "mysql-host=mysql.mysql-system.svc.cluster.local"
  - "mysql-username=lgtmp"
  - "mysql-password=VD538OYxSEiGD4I9mmFfqFMCGq1vIiGm"

# integrations memcached credentials
- name: integrations-memcached-secret
  namespace: monitoring-system
  options:
    disableNameSuffixHash: true
  literals:
  - "memcached-address=memcached.memcached-system.svc.cluster.local:11211"

# integrations redis credentials
- name: integrations-redis-secret
  namespace: monitoring-system
  options:
    disableNameSuffixHash: true
  literals:
  - "redis-addr=redis-master.redis-system.svc.cluster.local:6379"
  - "redis-password=VD538OYxSEiGD4I9mmFfqFMCGq1vIiGm"
