apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring-system

helmCharts:
- name: grafana-agent
  version: 0.27.2
  repo: https://grafana.github.io/helm-charts
  releaseName: grafana-agent
  namespace: monitoring-system
  includeCRDs: false
  valuesFile: values-k3d-k3s.yaml

configMapGenerator:
- name: agent-config
  files:
  - configs/config.river

- name: agent-modules
  files:
  - configs/modules/lgtmp.river
  - configs/modules/logs.river
  - configs/modules/profiles.river
  - configs/modules/metrics.river


secretGenerator:
- name: agent-env
  literals:
  - AGENT_LOG_LEVEL=info
  - AGENT_CONFIG_FOLDER=/etc/agent-modules
  - CLUSTER=k3d-k3s-codelab
  - METRICS_ENDPOINT=http://nginx.monitoring-system:8080
  - LOGS_ENDPOINT=http://loki-gateway.logging-system.svc.cluster.local:80
  - PROFILES_ENDPOINT=http://pyroscope.profiles-system:4040

