crds:
  create: false
agent:
  enableReporting: false
  mode: 'flow'
  configMap:
    create: false
    name: agent-config
    key: config.river
  clustering:
    enabled: true
  envFrom:
  - secretRef:
      name: agent-env
      optional: true
  mounts:
    # -- Mount /var/log from the host into the container for log collection.
    varlog: true
    extra:
    - name: agent-modules
      mountPath: /etc/agent-modules
  extraPorts:
  - name: "grpc-otlp"
    port: 4317
    targetPort: 4317
    protocol: "TCP"
  - name: "http-otlp"
    port: 4318
    targetPort: 4318
    protocol: "TCP"
  - name: "zipkin"
    port: 9411
    targetPort: 9411
    protocol: "TCP"

serviceMonitor:
  enabled: true

ingress:
  enabled: true
  faroPort: 80
  hosts:
  - grafana-agent.localhost
  - agent.localhost

controller:
  type: daemonset
  volumes:
    extra:
    - name: agent-modules
      configMap:
        name: agent-modules
  podAnnotations:
    # https://github.com/grafana/agent-modules/tree/main/modules/kubernetes
    logs.agent.grafana.com/scrape: "true"
    logs.agent.grafana.com/scrub-level: "debug" # Boolean whether or not the level should be dropped from the log message (as it is a label).
    # logs.agent.grafana.com/tenant: ".*"       # Allow a pod to override the tenant for its logs.
    profiles.grafana.com/memory.scrape: "true"
    profiles.grafana.com/memory.port_name: "http-metrics"
    profiles.grafana.com/cpu.scrape: "true"
    profiles.grafana.com/cpu.port_name: "http-metrics"
    profiles.grafana.com/goroutine.scrape: "true"
    profiles.grafana.com/goroutine.port_name: "http-metrics"
  nodeSelector:
    kubernetes.io/os: linux