apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: k3s-codelab
servers: 1
agents: 2
kubeAPI:
  hostIP: "127.0.0.1"
  hostPort: "6550"
image: rancher/k3s:v1.27.4-k3s1
ports:
- port: 8080:80
  nodeFilters:
  - loadbalancer
- port: 8443:443
  nodeFilters:
  - loadbalancer