# ----------------------------------------------------
# apiVersion and kind of Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- metrics/k8s-all-in-one.yaml
- logs/namespace.yaml
- logs/loki/k8s-all-in-one.yaml
- profiles/namespace.yaml
- profiles/pyroscope/k8s-all-in-one.yaml
- traces/namespace.yaml
- traces/tempo/k8s-all-in-one.yaml
- grafana-datasources-all-in-one.yaml


secretGenerator:
- name: agent-env
  namespace: monitoring-system
  behavior: replace
  options:
    disableNameSuffixHash: true
  literals:
  - TRACES_ENDPOINT=tempo.tracing-system.svc.cluster.local:4317

# replace grafana-env
- name: grafana-env
  namespace: monitoring-system
  options:
    disableNameSuffixHash: true
  literals:
  - NAMESPACE=monitoring-system
  - GF_LOG_LEVEL=warn
  - GF_TRACING_OPENTELEMETRY_OTLP_ADDRESS=grafana-agent.monitoring-system:4317
  - GF_TRACING_OPENTELEMETRY_CUSTOM_ATTRIBUTES=cluster:k3d-k3s-codelab,namespace:monitoring-system
  - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor,dashgpt

- name: loki-env
  namespace: logging-system
  literals:
  - LOKI_S3_SECRET_ACCESS_KEY=VD538OYxSEiGD4I9mmFfqFMCGq1vIiGm

- name: pyroscope-env
  namespace: profiles-system
  literals:
  - PYROSCOPE_STORAGE_S3_ENDPOINT=minio.minio-system.svc.cluster.local:443
  - PYROSCOPE_STORAGE_S3_ACCESS_KEY_ID=lgtmp
  - PYROSCOPE_STORAGE_S3_SECRET_ACCESS_KEY=VD538OYxSEiGD4I9mmFfqFMCGq1vIiGm

- name: tempo-env
  namespace: tracing-system
  literals:
  - TEMPO_S3_ENDPOINT=minio.minio-system.svc:443
  - TEMPO_S3_ACCESS_KEY=lgtmp
  - TEMPO_S3_SECRET_KEY=VD538OYxSEiGD4I9mmFfqFMCGq1vIiGm

configMapGenerator:
- name: loki-config
  namespace: logging-system
  behavior: replace
  files:
  - config.yaml=logs/configs/loki.yaml

- name: pyroscope-config
  namespace: profiles-system
  options:
    disableNameSuffixHash: true
  behavior: replace
  files:
  - config.yaml=profiles/configs/pyroscope.yaml

- name: tempo
  namespace: tracing-system
  behavior: replace
  files:
  - tempo.yaml
  - traces/configs/overrides.yaml

# replace nginx-templates and nginx-env configMap
- name: nginx-templates
  namespace: gateway
  options:
    disableNameSuffixHash: true
  files:
  - logs/configs/gateway_loki.conf.template
  - metrics/configs/gateway_mimir.conf.template
  - profiles/configs/gateway_pyroscope.conf.template
  - traces/configs/gateway_tempo.conf.template
- name: nginx-env
  namespace: gateway
  options:
    disableNameSuffixHash: true
  # We need to fully set all variables because nginx envsubst does not support default values.
  # https://github.com/nginxinc/docker-nginx/issues/592
  literals:
  - LOKI_DISTRIBUTOR_HOST=loki.logging-system.svc.cluster.local
  - LOKI_INGESTER_HOST=loki.logging-system.svc.cluster.local
  - LOKI_RULER_HOST=loki.logging-system.svc.cluster.local
  - LOKI_COMPACTOR_HOST=loki.logging-system.svc.cluster.local
  - LOKI_QUERIER_HOST=loki.logging-system.svc.cluster.local
  - LOKI_QUERY_FRONTEND_HOST=loki.logging-system.svc.cluster.local

  - MIMIR_DISTRIBUTOR_HOST=mimir.monitoring-system.svc.cluster.local
  - MIMIR_QUERY_FRONTEND_HOST=mimir.monitoring-system.svc.cluster.local
  - MIMIR_ALERT_MANAGER_HOST=mimir.monitoring-system.svc.cluster.local
  - MIMIR_RULER_HOST=mimir.monitoring-system.svc.cluster.local
  - MIMIR_COMPACTOR_HOST=mimir.monitoring-system.svc.cluster.local

  - PYROSCOPE_DISTRIBUTOR_HOST=pyroscope.profiles-system.svc.cluster.local
  - PYROSCOPE_QUERY_FRONTEND_HOST=pyroscope.profiles-system.svc.cluster.local

  - TEMPO_DISTRIBUTOR_HOST=tempo.tracing-system.svc.cluster.local
  - TEMPO_INGESTER_HOST=tempo.tracing-system.svc.cluster.local
  - TEMPO_QUERY_FRONTEND_HOST=tempo.tracing-system.svc.cluster.local
  - TEMPO_COMPACTOR_HOST=tempo.tracing-system.svc.cluster.local
