apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: operator
  version: 5.0.11
  repo: https://operator.min.io
  releaseName: operator
  namespace: minio-system
  includeCRDs: false
  valuesFile: values-k3d-k3s.yaml

resources:
- namespace.yaml
