operator:
  replicaCount: 1
  resources:
    requests:
      cpu: 10m
      memory: 55Mi
      ephemeral-storage: 128Mi
    limits:
      cpu: 999m
      memory: 1Gi

console:
  resources:
    requests:
      cpu: 10m
      memory: 55Mi
    limits:
      cpu: 999m
      memory: 1Gi
  ingress:
    enabled: true
    host: console.localhost

# http://console.localhost:8080
# kubectl get secret/console-sa-secret -n minio-system -o json | jq -r ".data.token" | base64 -d
