operator:
  replicaCount: 1
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
      ephemeral-storage: 128Mi
    limits:
      cpu: 1000m
      memory: 1024Mi

console:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 1024Mi
  ingress:
    enabled: true
    host: console.localhost

# http://console.localhost:8080
# kubectl get secret/console-sa-secret -n minio-system -o json | jq -r ".data.token" | base64 -d
