apiVersion: 1

datasources:
# Mimir for metrics
- name: Metrics
  type: prometheus
  uid: metrics
  access: proxy
  orgId: 1
  url: http://gateway:8080/prometheus
  basicAuth: false
  isDefault: true # Note: default datasources
  version: 1
  editable: true

# Loki for logs
- name: Logs
  type: loki
  access: proxy
  orgId: 1
  uid: logs
  url: http://gateway:3100
  basicAuth: false
  isDefault: false
  version: 1
  editable: true
