apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring-system

helmCharts:
- name: grafana
  version: 7.0.15
  repo: https://grafana.github.io/helm-charts
  releaseName: grafana
  namespace: monitoring-system
  includeCRDs: false
  skipTests: true
  valuesFile: values-k3d-k3s.yaml

resources:
- namespace.yaml

images:
- name: docker.io/grafana/grafana
  newTag: 10.2.2

configMapGenerator:
- name: grafana
  files:
  - configs/grafana.ini

- name: grafana-datasources
  options:
    immutable: true
    labels:
      grafana_datasource: "1"
  files:
  - configs/datasources.yaml

- name: minio-dashboard.json
  options:
    labels:
      grafana_dashboard: "1"
    annotations:
      grafana_dashboard_folder: "/dashboards"
  files:
  - configs/minio-dashboard.json

secretGenerator:
- name: grafana-secret
  literals:
  - admin-user=admin
  - admin-password=admin_password
- name: grafana-env
  options:
    disableNameSuffixHash: true
  literals:
  - NAMESPACE=monitoring-system
  - GF_LOG_LEVEL=info
