# For more information on this configuration, see the complete reference guide at
# https://grafana.com/docs/tempo/latest/configuration/

multitenancy_enabled: false
usage_report:
  reporting_enabled: false

compactor:
  compaction:
    block_retention: 1h

distributor:
  receivers:
    otlp:
      protocols:
        http:
        grpc:

ingester:
  max_block_duration: 5m

memberlist:
  join_members:
  - tempo-memberlist:7946

querier:
  frontend_worker:
    frontend_address: tempo-memberlist:9095

server:
  grpc_server_max_recv_msg_size: 4194304
  grpc_server_max_send_msg_size: 4194304
  http_listen_port: 3100
  grpc_listen_port: 9095
  log_level: warn

storage:
  trace:
    backend: s3
    wal:
      path: /tmp/tempo/wal
    s3:
      bucket: tempo-data
      endpoint: ${TEMPO_S3_ENDPOINT:-minio:9000}
      access_key: ${TEMPO_S3_ACCESS_KEY:-lgtmp}
      secret_key: ${TEMPO_S3_SECRET_KEY:-supersecret}
      insecure: ${TEMPO_S3_INSECURE:-true}
      tls_insecure_skip_verify: true