multitenancy_enabled: false
usage_report:
  reporting_enabled: false
compactor:
  compaction:
    block_retention: 1h
distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
ingester:
  max_block_duration: 5m
query_frontend:
  search:
    duration_slo: 5s
    throughput_bytes_slo: 1.073741824e+09
  trace_by_id:
    duration_slo: 5s
server:
  http_listen_port: 3100
  grpc_listen_port: 9095
  log_level: debug
storage:
  trace:
    backend: s3
    wal:
      path: /tmp/tempo/wal
    s3:
      bucket: tempo-data
      endpoint: ${TEMPO_S3_ENDPOINT:minio.minio-system.svc:443}
      access_key: ${TEMPO_S3_ACCESS_KEY:lgtmp}
      secret_key: ${TEMPO_S3_SECRET_KEY:supersecret}
      insecure: ${TEMPO_S3_INSECURE:false}
      tls_insecure_skip_verify: true
overrides:
  per_tenant_override_config: /conf/overrides.yaml
  # Global ingestion limits configurations
  # https://grafana.com/docs/tempo/latest/configuration/#overrides
  defaults:
    metrics_generator:
      processors:
      - service-graphs
      - span-metrics
      - local-blocks

metrics_generator:
  storage:
    path: "/tmp/tempo"
    remote_write:
    - name: metrics-primary
      url: http://nginx.gateway.svc.cluster.local:8080/api/v1/push
      send_exemplars: true
      headers:
        X-Scope-OrgID: "anonymous"