overrides:
  "anonymous":
    ingestion:
      rate_strategy: local
      rate_limit_bytes: 15000000
      burst_size_bytes: 20000000
      max_traces_per_user: 10000
    read:
      max_bytes_per_tag_values_query: 5000000
    # global:
    #   max_bytes_per_trace: 1500000
    # metrics_generator:
    #   processors:
    #   - service-graphs
    #   - span-metrics
    #   remote_write_headers:
    #     X-Scope-OrgID: "anonymous"
