name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - main
  workflow_dispatch: {}

jobs:
  update_release_draft:
    name: Trigger a draft release update
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "main"
      - uses: release-drafter/release-drafter@v6
        id: draft
        env:
          GITHUB_TOKEN: ${{ secrets.QCBOT_TOKEN }}
        with:
          commitish: main

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
      - name: Copy release notes from Draft
        run: |
          tag_name=${{ steps.draft.outputs.tag_name }}
          echo "${{ steps.draft.outputs.body }}" > docs/release_notes/${tag_name:1}.md
      - name: Upsert Pull Request
        uses: peter-evans/create-pull-request@70a41aba780001da0a30141984ae2a0c95d8704e #v6.0.2
        with:
          token: ${{ secrets.QCBOT_TOKEN }}
          title: Add release notes for ${{ steps.draft.outputs.tag_name }}
          commit-message: Add release notes for ${{ steps.draft.outputs.tag_name }}
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          signoff: true
          # author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          assignees: qclaogui
          # reviewers: qclaogui
          body: |
            🤖 Copy release notes from Draft

            <details>
            <summary> Full draft release notes for ${{ steps.draft.outputs.tag_name }} </summary>
            <blockquote>

            ${{ steps.draft.outputs.body }}
            
            </blockquote>
            </details>
            <br />

            > Auto-generated by [Release Drafter GitHub Action][0]

            [0]: https://github.com/qclaogui/codelab-monitoring/blob/main/.github/workflows/release-drafter.yml
          labels: kind/docs, skip-release-notes
          branch: update-release-notes
          draft: true
